### ISSUE TITLE
宝塔docker搭建后出现的问题

### ISSUE THREAD

**Issue by HaiVong** [adams549659584/go-proxy-bingai#1]
使用宝塔的docker搭建这个项目，会出现“**很抱歉，似乎出现错误。 让我们重新开始吧。**”这个错误。
刚开始搭建完是没问题的，但是在使用一会后就出现问题
并且填写了cookie后，想要生成图片也会报上面的错误。
需要清楚浏览器缓存后才能正常问答，但是依然无法生成图片

**Comment by adams549659584** [comment]
基本只能靠刷新大法，全部参数都是原路传给微软的，我看看有没有什么隐藏bug
