### ISSUE TITLE
关于不同平台部署

### ISSUE THREAD

**Issue by KFC-vme-50** [adams549659584/go-proxy-bingai#10]
我实测下来，render，replit和vercel都能成功实现。
但是，在我绑定域名之后只有在vercel部署的网页会出现问题，直接访问我绑定在vercel的域名会显示重定向次数过多。其他平台都没有问题。

**Comment by adams549659584** [comment]
看了下我Vercel部署的还能用啊，你是最新代码部署的吗？可以看看cookie，有个 BingAI_Rand_IP，看看是啥？
