### ISSUE TITLE
我让他帮我检查代码，他让我复制到他的回答中，我发现复制不了，能不能修复下？

### ISSUE THREAD

**Issue by tutianyu101** [adams549659584/go-proxy-bingai#100]
![微信截图_20230527214409](https://github.com/adams549659584/go-proxy-bingai/assets/134258491/cddc808f-592b-4fa5-aa3d-c7e3150ed4e3)
上面写请复制到这里，我尝试了很多方法都复制不上去，请问能不能修复下？

**Comment by tutianyu101** [comment]
他原来的网站好像可以复制进他的代码块

**Comment by adams549659584** [comment]
![image](https://github.com/adams549659584/go-proxy-bingai/assets/10492939/d1477fd9-1e79-438d-a70c-4fd0a908b676)

我去官网试了下，是这样的啊，怎样可以触发？

**Comment by lwd-temp** [comment]
它的意思应该是像这样输入代码：

\`\`\`
代码
\`\`\`

但是Markdown直接被渲染了，成了这个样子。

**Comment by QwindF** [comment]
![image](https://github.com/adams549659584/go-proxy-bingai/assets/87116340/0ac6f650-3b5d-4594-979a-538026875fb3)
粘贴到这里就行
