### ISSUE TITLE
html中的Upgrade Insecure Requests导致非127地址循环加载

### ISSUE THREAD

**Issue by expvintl** [adams549659584/go-proxy-bingai#101]
我在多个内网设备中测试，发现
```
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
```
标签会导致外网，或者其他设备在访问其js css之类的资源的时候会强制使用https去加载导致无法访问资源，服务端本身没有用https的
![5750e9fe0c867aa9.png](https://github.com/adams549659584/go-proxy-bingai/assets/16302731/2cbaeed0-4c6d-4392-94cd-c1003060b4bf)

希望看看能不能修一下

**Comment by adams549659584** [comment]
除了 localhost ，暂时只支持 https 域名访问的

**Comment by QwindF** [comment]
> 除了 localhost ，暂时只支持 https 域名访问的
这个是什么原因限制的？

**Comment by adams549659584** [comment]
前后端都有限制的， 只有在HTTPS的情况下，浏览器 Accept-Encoding 才会包含 br , localhost 除外，但是微软那边响应基本只响应 br 头，浏览器不包含就会解密失败。
