### ISSUE TITLE
部署好了。也HTTPS了。出现这个问题啥原因

### ISSUE THREAD

**Issue by wyongmin** [adams549659584/go-proxy-bingai#102]
很抱歉，似乎出现错误。 让我们重新开始吧。

**Comment by adams549659584** [comment]
这样看不出什么问题，部署参考下 #71

**Comment by QwindF** [comment]
> 很抱歉，似乎出现错误。 让我们重新开始吧。

网络问题，国内机子要用梯子

**Comment by wahha2003** [comment]
> > 很抱歉，似乎出现错误。 让我们重新开始吧。
> 
> 网络问题，国内机子要用梯子

我是美国机子，搭好以后用的本站聊天服务器，然后用的本站聊天服务器。也是出现这个问题。是不是还要在本地安装浏览器插件才行
