### ISSUE TITLE
每次打开都要重置才能不出现重新开始

### ISSUE THREAD

**Issue by deeme** [adams549659584/go-proxy-bingai#103]
输入账号刷新，用账号又出现重新开始，没法聊天画图，彻底失效，必须重置后游客才能聊天
内置账号也是不行，不能聊天
测试使用作者的主站，游客不用重置，设置账号后刷新，能聊天出现历史记录，但是不能画图，设置里的画图也不行提示要登录
这是什么原因造成的？

**Comment by adams549659584** [comment]
不清楚，感觉账号不对，我这边试了正常的
