### ISSUE TITLE
docker 实例过久未重启出现 创建会话ID失败

### ISSUE THREAD

**Issue by z0z0r4** [adams549659584/go-proxy-bingai#104]
我的机子在香港，但直接访问 `http://localhost:8080/turing/conversation/create` 返回的还是空的

![image](https://github.com/adams549659584/go-proxy-bingai/assets/78744121/de00a072-794b-4d7f-b12c-06148cab3de8)

![image](https://github.com/adams549659584/go-proxy-bingai/assets/78744121/adc831e2-d49a-4cae-a924-cdec53d02e31)

然而当我重启 docker 之后，又恢复了，稳定复现

![image](https://github.com/adams549659584/go-proxy-bingai/assets/78744121/ae607059-a326-401d-b63c-dc2a91f4294e)

大概不到一天不重启又会出现上述情况

ssh 日志如下
```
root@VM-4-4-debian  ~  curl 127.0.0.1:8080/turing/conversation/create

root@VM-4-4-debian  ~  docker ps
CONTAINER ID   IMAGE                            COMMAND                  CREATED      STATUS       PORTS                                       NAMES
0ee8ba016376   adams549659584/go-proxy-bingai   "/app/go-proxy-bingai"   7 days ago   Up 7 hours   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp   go-proxy-bingai

root@VM-4-4-debian  ~  docker restart go-proxy-bingai
go-proxy-bingai

root@VM-4-4-debian  ~  curl 127.0.0.1:8080/turing/conversation/create
{"conversationId":"51D|BingProdUnAuthenticatedUsers|2EB7F6A1FC26EEC2D1BBC5C3B758DD748FA149EDF417A402C7F07AB8A271F659","clientId":"0BE824215A1A69C03470373E5BC36879","conversationSignature":"uzsZayJYtD9sex0rkQ5pE68LSkIpkO4ZSOyj2vogaCM=","result":{"value":"Success","message":null}}
```

目测并非被墙导致的问题...

**Comment by z0z0r4** [comment]
bing 未登录

**Comment by adams549659584** [comment]
![image](https://github.com/adams549659584/go-proxy-bingai/assets/10492939/c7f305b1-42a4-4012-b2a6-18c60379f8a4)
主站已经快3天没重启了，也没出现

**Comment by wyongmin** [comment]
你们用代理了吗。

**Comment by adams549659584** [comment]
不用，我们的可以直连 www.bing.com 的

**Comment by z0z0r4** [comment]
我选择放弃.jpg
