### ISSUE TITLE
打开之后，浏览器插件vi起冲突

### ISSUE THREAD

**Issue by justincnn** [adams549659584/go-proxy-bingai#105]
在输入框输入x（定义：关闭tab），r(刷新tab)等字母，会直接关闭或者刷新，
而不是正常的输入内容，

这个问题会经常出现，但又不是每次都出现

换了vi插件，还是这个情况，

**Comment by adams549659584** [comment]
没用过，这种算插件影响了网站的正常使用吧？应该向插件提 issue ？
