### ISSUE TITLE
 很抱歉，你已达到可在 24 小时内发送到必应的邮件限制。请稍后回来查看!怎么解决大佬

### ISSUE THREAD

**Issue by wlxgx** [adams549659584/go-proxy-bingai#106]
刷新和cookie不顶用啊

**Comment by adams549659584** [comment]
服务端配置 cookie ，多人使用了？登录账号无解，匿名可以刷新或一键重置

**Comment by showlee** [comment]
我也遇到同样的问题"很抱歉，你已达到可在 24 小时内发送到必应的邮件限制。请稍后回来查看!"，应该怎么解决这个问题呢？

**Comment by adams549659584** [comment]
登录账号的只能等第二天，匿名的一般刷新就好

**Comment by showlee** [comment]
> 登录账号的只能等第二天，匿名的一般刷新就好

请问：填写了账号cookie(也就是相当于登陆了账号)，还能重新返回到匿名模式吗？

**Comment by adams549659584** [comment]
一键重置

**Comment by showlee** [comment]
> 一键重置

哈哈哈哈，还真短路忘了这茬儿，谢谢！

**Comment by FlyongX** [comment]
我也出现了这个问题，发现是帐号没有资格使用New Bing的原因。需要先加入等候名单，现在开放访问了，如果帐号没有被拉黑，应该会秒过，然后就可以正常使用了。
