### ISSUE TITLE
部署之后打不开，一直加载什么问题

### ISSUE THREAD

**Issue by luowei729** [adams549659584/go-proxy-bingai#11]
![image](https://github.com/adams549659584/go-proxy-bingai/assets/10611605/86740bc4-6462-49bf-84d3-65cb9211e452)

**Comment by adams549659584** [comment]
加载js失败了，不是https的？域名用localhost试试，不然就要https了，只有在 http 的情况下，浏览器 Accept-Encoding 才会包含 br , localhost 除外。一般是浏览器发出的请求要的内容是 gzip 之类的，但是微软响应的内容是 br 压缩的，就不解密了

**Comment by adams549659584** [comment]
微软已经逐步开放未登录用户的权限了，基本只有画图需要用到登录的

**Comment by luowei729** [comment]
我测试过用自己的小号cookies，一周了没有封号

![image](https://github.com/adams549659584/go-proxy-bingai/assets/10611605/8f92d177-45b7-46a6-b7d8-16a5760337ad)

**Comment by luowei729** [comment]
> 微软已经逐步开放未登录用户的权限了，基本只有画图需要用到登录的

不行的，还是要登录，看上图

**Comment by adams549659584** [comment]
有时候会出现，还是不稳定，一般刷新就能用了

**Comment by luowei729** [comment]
目的就是降低使用门槛

**Comment by adams549659584** [comment]
这样很快就会触发图形验证，而且很快就达到24小时限制，已经测试了

**Comment by gityuh** [comment]
这个问题是因为源代码里面index.html里面放了百度统计和谷歌统计，这个两个统计都去掉
因为内网访问外网会受阻，外网访问内网也会受阻。

**Comment by adams549659584** [comment]
![1684462447129](https://github.com/adams549659584/go-proxy-bingai/assets/10492939/dfe5faea-40a3-4a4e-ab11-02e94ae649b6)
async 和 动态生成 并不会阻塞
