### ISSUE TITLE
文章撰写也希望加入服务选择

### ISSUE THREAD

**Issue by Do1e** [adams549659584/go-proxy-bingai#111]
如题，目前文章撰写还是使用默认的bing服务器。

![image](https://github.com/adams549659584/go-proxy-bingai/assets/73533898/f62fc2cf-b37a-48bc-bfbc-e27c3aeee04e)

**Comment by adams549659584** [comment]
1.8.1 有改了默认使用聊天界面选择的，你在聊天界面一键重置下试试

**Comment by Do1e** [comment]
不行的，Chat里面选择了服务，并且是可用的，但是compose里面无法使用，看控制台还是尝试连接Sydney

**Comment by adams549659584** [comment]
> 不行的，Chat里面选择了服务，并且是可用的，但是compose里面无法使用，看控制台还是尝试连接Sydney

大概知道哪里问题了，下次版本更新下

**Comment by adams549659584** [comment]
新版已修复使用聊天界面选择的服务
