### ISSUE TITLE
发现一个可以利用的BUG

### ISSUE THREAD

**Issue by yeayee** [adams549659584/go-proxy-bingai#113]
WSS请求官网，使用魔法后的cookies，在停止魔法之后，仍旧可以对话；
因此能不能把_U部分改为，或者增加一个完整自定义cookies的输入框。
这样可以大幅度减小你们服务器的压力。

**Comment by adams549659584** [comment]
wss那个似乎没有携带cookie的，只看ip，请求头带上 X-Forwarded-For 改非国内ip就可以连，不然就连不上了
