### ISSUE TITLE
无法开启对话

### ISSUE THREAD

**Issue by wahha2003** [adams549659584/go-proxy-bingai#115]
docker部署，1.8.1版本，美国服务器。用的本站聊天服务器，能够正常检测出延迟，但是不论输入什么问题就会显示 "很抱歉，似乎出现错误。 让我们重新开始吧。"控制台也没有相关的报错好像
![6](https://github.com/adams549659584/go-proxy-bingai/assets/104408266/b6aa361c-5038-4902-9fe8-3c30c6c8796b)

**Comment by wahha2003** [comment]
大佬帮忙看看这是啥情况

**Comment by adams549659584** [comment]
是不是直接用 ip 访问了？需要添加域名 ，https 访问的

**Comment by wahha2003** [comment]
> 是不是直接用 ip 访问了？需要添加域名 ，https 访问的，参考下 #71

并没有，就是docker部署然后Nginx反代的，开了https

**Comment by adams549659584** [comment]
> > 是不是直接用 ip 访问了？需要添加域名 ，https 访问的，参考下 #71
> 
> 并没有，就是docker部署然后Nginx反代的，开了https

那不清楚怎么回事了，没看出什么有用的信息
