### ISSUE TITLE
更新到1.8.5后，仍然不能切换对话样式

### ISSUE THREAD

**Issue by mwnu** [adams549659584/go-proxy-bingai#118]
触发条件：首次对话之后，再切换对话样式，发送问题，就会变成：“正在尝试连接，请稍侯”
![2](https://github.com/adams549659584/go-proxy-bingai/assets/45463732/aec9cf3a-e2eb-47c7-b5ee-96cdc06fc6b6)

我已经配置了nginx，外网以https+端口的形式访问页面，前端会错误请求默认443端口的url，而不是我配置的7878端口：
```
https://我的域名/turing/conversation/chats
https://我的域名/cdx/bg-sprite.png
https://我的域名/turing/conversation/create
```
控制台出现错误：
![Snipaste_2023-05-30_12-20-44](https://github.com/adams549659584/go-proxy-bingai/assets/45463732/c4cce402-b25a-48ec-9182-86530568d2a4)

**Comment by mwnu** [comment]
> 触发条件：首次对话之后，再切换对话样式，发送问题，就会变成：“正在尝试连接，请稍侯” ![2](https://user-images.githubusercontent.com/45463732/241847477-aec9cf3a-e2eb-47c7-b5ee-96cdc06fc6b6.png)
> 
> 我已经配置了nginx，外网以https+端口的形式访问页面，前端会错误请求默认端口（443）的url：
> 
> ```
> https://我的域名/turing/conversation/chats
> https://我的域名/cdx/bg-sprite.png
> https://我的域名/turing/conversation/create
> ```
> 
> 控制台出现错误： ![Snipaste_2023-05-30_12-20-44](https://user-images.githubusercontent.com/45463732/241847506-c4cce402-b25a-48ec-9182-86530568d2a4.png)

**Comment by adams549659584** [comment]
那可能就是端口问题，暂时无法解决，在我的演示站正常吗？

**Comment by mwnu** [comment]
> 那可能就是端口问题，暂时无法解决，在我的演示站正常吗？

演示站正常
