### ISSUE TITLE
大佬问下设置用户后，是我本人专属的，还是其他人访问网页也可以用我的账户？

### ISSUE THREAD

**Issue by tutianyu101** [adams549659584/go-proxy-bingai#119]
恢复匿名的话直接一键重置吗？1.8.5是不是可以自动更新服务端版本了？

**Comment by tutianyu101** [comment]
还有大佬为什么我登陆账号后，还是只能问10句啊，我登陆账号后提示还是10条

**Comment by tutianyu101** [comment]
> 在页面设置的用户是你自己专属的。 如果你自己部署了站点，在服务端设置用户，其他人未登录就会用你设置的

哦哦好的大佬我没在服务端设置用户，服务端怎么设置用户的？大佬，我发现设置用户好像可以规避会话ID创建失败

**Comment by tutianyu101** [comment]
> 在页面设置的用户是你自己专属的。 如果你自己部署了站点，在服务端设置用户，其他人未登录就会用你设置的

大佬我在页面上面设置用户后，很久没出现会话id创建失败了。不知道会不会有关系

**Comment by adams549659584** [comment]
环境变量那里有写，自己用可以设置下，多人使用最好不要，会触发 cloudflare 验证，暂时需要去 www.bing.com 才能过验证，也很快会触发24小时限制。
一般都是未登录的会创建会话失败的，所以那10次重试也是针对未登录用户，进页面就会尝试创建会话Id了。

**Comment by tutianyu101** [comment]
> 环境变量那里有写，自己用可以设置下，多人使用最好不要，会触发 cloudflare 验证，暂时需要去 [www.bing.com](http://www.bing.com) 才能过验证，也很快会触发24小时限制。 一般都是未登录的会创建会话失败的，所以那10次重试也是针对未登录用户，进页面就会尝试创建会话Id了。

还有个autoupdate是自动升级服务端版本的意思吗？我看1.8.5写的。谢谢大佬

**Comment by adams549659584** [comment]
> > 环境变量那里有写，自己用可以设置下，多人使用最好不要，会触发 cloudflare 验证，暂时需要去 [www.bing.com](http://www.bing.com) 才能过验证，也很快会触发24小时限制。 一般都是未登录的会创建会话失败的，所以那10次重试也是针对未登录用户，进页面就会尝试创建会话Id了。
> 
> 还有个autoupdate是自动升级服务端版本的意思吗？我看1.8.5写的。谢谢大佬

不是，是前端页面的，现在用了 pwa，会在本地缓存页面及所有资源，一般有 autoUpdate 和 prompt 两种更新方式，弹窗给用户选择暂时有点问题，就切换回自动了，不过这样就是看浏览器想什么时候更新了

**Comment by tutianyu101** [comment]
> > > 环境变量那里有写，自己用可以设置下，多人使用最好不要，会触发 cloudflare 验证，暂时需要去 [www.bing.com](http://www.bing.com) 才能过验证，也很快会触发24小时限制。 一般都是未登录的会创建会话失败的，所以那10次重试也是针对未登录用户，进页面就会尝试创建会话Id了。
> > 
> > 
> > 还有个autoupdate是自动升级服务端版本的意思吗？我看1.8.5写的。谢谢大佬
> 
> 不是，是前端页面的，现在用了 pwa，会在本地缓存页面及所有资源，一般有 autoUpdate 和 prompt 两种更新方式，弹窗给用户选择暂时有点问题，就切换回自动了，不过这样就是看浏览器想什么时候更新了

大佬今天你的演示站也好多次创建会话id失败了，感觉昨天也没这么多次，这真的绕不过去吗

**Comment by adams549659584** [comment]
> > > > 环境变量那里有写，自己用可以设置下，多人使用最好不要，会触发 cloudflare 验证，暂时需要去 [www.bing.com](http://www.bing.com) 才能过验证，也很快会触发24小时限制。 一般都是未登录的会创建会话失败的，所以那10次重试也是针对未登录用户，进页面就会尝试创建会话Id了。
> > > 
> > > 
> > > 还有个autoupdate是自动升级服务端版本的意思吗？我看1.8.5写的。谢谢大佬
> > 
> > 
> > 不是，是前端页面的，现在用了 pwa，会在本地缓存页面及所有资源，一般有 autoUpdate 和 prompt 两种更新方式，弹窗给用户选择暂时有点问题，就切换回自动了，不过这样就是看浏览器想什么时候更新了
> 
> 大佬今天你的演示站也好多次创建会话id失败了，感觉昨天也没这么多次，这真的绕不过去吗

太多人访问了，演示站今天 PV 已经5万多了，可能很快挂了

**Comment by tutianyu101** [comment]
> > > > > 环境变量那里有写，自己用可以设置下，多人使用最好不要，会触发 cloudflare 验证，暂时需要去 [www.bing.com](http://www.bing.com) 才能过验证，也很快会触发24小时限制。 一般都是未登录的会创建会话失败的，所以那10次重试也是针对未登录用户，进页面就会尝试创建会话Id了。
> > > > 
> > > > 
> > > > 还有个autoupdate是自动升级服务端版本的意思吗？我看1.8.5写的。谢谢大佬
> > > 
> > > 
> > > 不是，是前端页面的，现在用了 pwa，会在本地缓存页面及所有资源，一般有 autoUpdate 和 prompt 两种更新方式，弹窗给用户选择暂时有点问题，就切换回自动了，不过这样就是看浏览器想什么时候更新了
> > 
> > 
> > 大佬今天你的演示站也好多次创建会话id失败了，感觉昨天也没这么多次，这真的绕不过去吗
> 
> 太多人访问了，演示站今天 PV 已经5万多了，可能很快挂了

大佬这个pv没关系吧，我说的是那个bing.vcanbb.top那个，今天也好多次会话id创建失败，一会就来一会就来，要命了

**Comment by adams549659584** [comment]
> > > > > > 环境变量那里有写，自己用可以设置下，多人使用最好不要，会触发 cloudflare 验证，暂时需要去 [www.bing.com](http://www.bing.com) 才能过验证，也很快会触发24小时限制。 一般都是未登录的会创建会话失败的，所以那10次重试也是针对未登录用户，进页面就会尝试创建会话Id了。
> > > > > 
> > > > > 
> > > > > 还有个autoupdate是自动升级服务端版本的意思吗？我看1.8.5写的。谢谢大佬
> > > > 
> > > > 
> > > > 不是，是前端页面的，现在用了 pwa，会在本地缓存页面及所有资源，一般有 autoUpdate 和 prompt 两种更新方式，弹窗给用户选择暂时有点问题，就切换回自动了，不过这样就是看浏览器想什么时候更新了
> > > 
> > > 
> > > 大佬今天你的演示站也好多次创建会话id失败了，感觉昨天也没这么多次，这真的绕不过去吗
> > 
> > 
> > 太多人访问了，演示站今天 PV 已经5万多了，可能很快挂了
> 
> 大佬这个pv没关系吧，我说的是那个bing.vcanbb.top那个，今天也好多次会话id创建失败，一会就来一会就来，要命了

多人同时使用就会出现了，之前高峰的时候基本10次都是失败，登录比较稳。

**Comment by tutianyu101** [comment]
> > > > > > > 环境变量那里有写，自己用可以设置下，多人使用最好不要，会触发 cloudflare 验证，暂时需要去 [www.bing.com](http://www.bing.com) 才能过验证，也很快会触发24小时限制。 一般都是未登录的会创建会话失败的，所以那10次重试也是针对未登录用户，进页面就会尝试创建会话Id了。
> > > > > > 
> > > > > > 
> > > > > > 还有个autoupdate是自动升级服务端版本的意思吗？我看1.8.5写的。谢谢大佬
> > > > > 
> > > > > 
> > > > > 不是，是前端页面的，现在用了 pwa，会在本地缓存页面及所有资源，一般有 autoUpdate 和 prompt 两种更新方式，弹窗给用户选择暂时有点问题，就切换回自动了，不过这样就是看浏览器想什么时候更新了
> > > > 
> > > > 
> > > > 大佬今天你的演示站也好多次创建会话id失败了，感觉昨天也没这么多次，这真的绕不过去吗
> > > 
> > > 
> > > 太多人访问了，演示站今天 PV 已经5万多了，可能很快挂了
> > 
> > 
> > 大佬这个pv没关系吧，我说的是那个bing.vcanbb.top那个，今天也好多次会话id创建失败，一会就来一会就来，要命了
> 
> 多人同时使用就会出现了，之前高峰的时候基本10次都是失败，登录比较稳。

大佬我部署的两个服务器出现这个会话id创建失败也可能是多人使用是嘛。对了大佬，为什么我部署的聊天服务器，一直没法用啊?https://bingai.tutianyu101.workers.dev/   大佬你试试可用吗？我在服务里面选择一直处于不可用

**Comment by tutianyu101** [comment]
> > > > > > > 环境变量那里有写，自己用可以设置下，多人使用最好不要，会触发 cloudflare 验证，暂时需要去 [www.bing.com](http://www.bing.com) 才能过验证，也很快会触发24小时限制。 一般都是未登录的会创建会话失败的，所以那10次重试也是针对未登录用户，进页面就会尝试创建会话Id了。
> > > > > > 
> > > > > > 
> > > > > > 还有个autoupdate是自动升级服务端版本的意思吗？我看1.8.5写的。谢谢大佬
> > > > > 
> > > > > 
> > > > > 不是，是前端页面的，现在用了 pwa，会在本地缓存页面及所有资源，一般有 autoUpdate 和 prompt 两种更新方式，弹窗给用户选择暂时有点问题，就切换回自动了，不过这样就是看浏览器想什么时候更新了
> > > > 
> > > > 
> > > > 大佬今天你的演示站也好多次创建会话id失败了，感觉昨天也没这么多次，这真的绕不过去吗
> > > 
> > > 
> > > 太多人访问了，演示站今天 PV 已经5万多了，可能很快挂了
> > 
> > 
> > 大佬这个pv没关系吧，我说的是那个bing.vcanbb.top那个，今天也好多次会话id创建失败，一会就来一会就来，要命了
> 
> 多人同时使用就会出现了，之前高峰的时候基本10次都是失败，登录比较稳。

大佬我按照教程创建的。。代码核对过没问题呀

**Comment by adams549659584** [comment]
绑个域名看看，原域名可能墙了

**Comment by fewk** [comment]
> 

哈哈，昨天B站就刷几介绍的视频，无一例外都是直接扔大佬的演示站在简介里，他们的粉丝就直接用了，哪懂自己部署
