### ISSUE TITLE
我使用的Render一键部署，目前点击版本显示的是1.81，我看最新已经是1.85了

### ISSUE THREAD

**Issue by ghost** [adams549659584/go-proxy-bingai#121]
我重新Sync了Blueprints，并没有获取到任何更新，我看Sync的是render.yaml，还望大佬帮助解决一下

**Comment by adams549659584** [comment]
![image](https://github.com/adams549659584/go-proxy-bingai/assets/10492939/b02e53fb-38d2-43d8-8d8f-4dc313c9dc28)
