### ISSUE TITLE
大佬，今天搞个授权弹窗，该如何消除？

### ISSUE THREAD

**Issue by SokWith** [adams549659584/go-proxy-bingai#123]
![image](https://github.com/adams549659584/go-proxy-bingai/assets/129967025/bd1006fe-1c9e-4107-8379-41d711168734)

**Comment by adams549659584** [comment]
你自己部署的站点？你设置了授权码环境变量就会弹的

**Comment by SokWith** [comment]
不好意思，看了下，确实设置了环境变量。只是上午都没有弹出来，才误会了
