### ISSUE TITLE
撰写文章无法生成答案

### ISSUE THREAD

**Issue by sclxzy** [adams549659584/go-proxy-bingai#125]
演示站、一键部署都和本地部署都试了，聊天和作图可以正常使用，但是撰写文章从来没有成功返回答案，请问大家有遇到同样问题吗？请求大佬帮助。已经尝试过modheaders方案。谢谢

**Comment by troilus** [comment]
没有遇到，是不是你网络环境的问题

**Comment by adams549659584** [comment]
现在撰写文章使用聊天页面选择的聊天服务器了，一键重置试试
