### ISSUE TITLE
为什么对话次数限定为10次了

### ISSUE THREAD

**Issue by liuyirong89** [adams549659584/go-proxy-bingai#128]
麻烦问下大佬，为什么更新1.8.6之后，newbing对话次数限定为10次了？
![image](https://github.com/adams549659584/go-proxy-bingai/assets/120556065/63c389c1-dccf-4718-b70d-ba25b66806af)

**Comment by adams549659584** [comment]
未登录一直都是10次的，已登录20次，只是修正了显示bug
