### ISSUE TITLE
大佬有没有考虑过把别的ai也套娃进去？比如文言一心？比如讯飞星火？

### ISSUE THREAD

**Issue by tutianyu101** [adams549659584/go-proxy-bingai#129]
可以一次提问多个ai回答，或者齿轮这里点一下可以切换其他ai这样的？百度的文言一心好像没啥限制的。可不可以把所有ai都融合在一起呢？

**Comment by adams549659584** [comment]
好像github已经有这样的项目了，而且这些可以直接用，没必要吧

**Comment by tutianyu101** [comment]
> 好像github已经有这样的项目了，而且这些可以直接用，没必要吧

大佬我觉得有必要啊。。很多人懒。想在一个页面里实现，我也是，不想开好多个。大佬你要是第一个实现了不得牛逼坏了，找工作也方便呀

**Comment by tutianyu101** [comment]
> 好像github已经有这样的项目了，而且这些可以直接用，没必要吧

而且有些问题bing回答的不太好要找别的ai回答
