### ISSUE TITLE
vercel一键部署后，访问异常

### ISSUE THREAD

**Issue by wintrue** [adams549659584/go-proxy-bingai#13]
链接出现404

![image](https://github.com/adams549659584/go-proxy-bingai/assets/6380530/2b6427b5-9b73-443c-8ac3-1aef6ab59783)
![image](https://github.com/adams549659584/go-proxy-bingai/assets/6380530/84a4b3a4-97cd-49a3-87e2-c0071a410d25)

![image](https://github.com/adams549659584/go-proxy-bingai/assets/6380530/69370b62-1050-4376-a18e-815666e65556)

**Comment by adams549659584** [comment]
在 vercel 看看日志，404的话，接口应该没部署成功吧

**Comment by wintrue** [comment]
> 在 vercel 看看日志，404的话，接口应该没部署成功吧

页面已经正常出来了

**Comment by adams549659584** [comment]
之前有用相同域名部署过吗？页面会有本地缓存的

**Comment by wintrue** [comment]
> 之前有用相同域名部署过吗？页面会有本地缓存的

看到vercel有个警告，Cache函数丢失...

**Comment by adams549659584** [comment]
![image](https://github.com/adams549659584/go-proxy-bingai/assets/10492939/0a22f276-a9dd-4dda-ab74-36c18f67afb6)
刚再一键部署了个，可以的

**Comment by wintrue** [comment]
> ![image](https://user-images.githubusercontent.com/10492939/237559888-0a22f276-a9dd-4dda-ab74-36c18f67afb6.png) 刚再一键部署了个，可以的

我重新部署了还是不行，奇怪了，404

**Comment by adams549659584** [comment]
![image](https://github.com/adams549659584/go-proxy-bingai/assets/10492939/8071da1b-28bb-43c7-99f4-97a5201a2158)
我这里看正常啊，是不是你的网络哪里阻止了？看最上面的话，你的网络应该走了代理，vercel 的域名应该被墙了，绑定个域名试试

**Comment by wintrue** [comment]
> ![image](https://user-images.githubusercontent.com/10492939/237561771-8071da1b-28bb-43c7-99f4-97a5201a2158.png) 我这里看正常啊，是不是你的网络哪里阻止了？看最上面的话，你的网络应该走了代理，vercel 的域名应该被墙了，绑定个域名试试

好吧，估计是代理的问题..

**Comment by gityuh** [comment]
![image](https://github.com/adams549659584/go-proxy-bingai/assets/1203735/eea42f54-3bbf-419f-9f0b-d6bfd9fe4f18)
哎，我也一样

**Comment by adams549659584** [comment]
你配置了服务端 cookie？这像多人使用触发 cloudflare 图形验证了，暂时过不了，要去 bing 官网验证下

**Comment by gityuh** [comment]
> ![图像](https://user-images.githubusercontent.com/1203735/239414355-eea42f54-3bbf-419f-9f0b-d6bfd9fe4f18.png)哎，我也一样

我做了两部操作，
一，Edge浏览器上面，账户退出重新登录一下
二，部署的域名只能在Edge浏览器中访问，我Edge可以访问，chrome不行，bing那边应该做了浏览器判断

**Comment by adams549659584** [comment]
![1684462548826](https://github.com/adams549659584/go-proxy-bingai/assets/10492939/8cecbf2b-8c12-4392-af93-25d0d8339432)
移动端和电脑端都有分别赋值对应的 edge 的
