### ISSUE TITLE
请问环境变量怎么设置

### ISSUE THREAD

**Issue by luckyEason** [adams549659584/go-proxy-bingai#132]
请问环境变量怎么设置，谢谢

**Comment by QwindF** [comment]
#56

**Comment by luckyEason** [comment]
render怎么设置呢

> #56

**Comment by luckyEason** [comment]
render怎么设置

**Comment by QwindF** [comment]
什么系统？

**Comment by QwindF** [comment]
都一键部署了，还要设置什么？

**Comment by adams549659584** [comment]
![image](https://github.com/adams549659584/go-proxy-bingai/assets/10492939/87129f83-f7b1-4134-ad31-db75b2ee6f97)

**Comment by builden** [comment]
vercel不支持websocket，可以考虑支持在env中设置开启了worker.js的Cloudflare地址

**Comment by luckyEason** [comment]
感谢大佬
