### ISSUE TITLE
如何将搭建好的网页服务选择内的cloudflare替换成自己搭建的服务

### ISSUE THREAD

**Issue by Nothingness-Void** [adams549659584/go-proxy-bingai#134]
如题，寻思自己搭建完了就不占用公共资源了，但是我分享出去后使用我分享网站的人，不太能强求他们会选择服务，或者添加自定义链接，所以想问问大佬能不能加进这一功能

**Comment by SokWith** [comment]
感觉是这个
![image](https://github.com/adams549659584/go-proxy-bingai/assets/129967025/b778d13a-a1f3-4f13-8d8b-360d065653b3)

**Comment by Nothingness-Void** [comment]
> 感觉是这个 ![image](https://user-images.githubusercontent.com/129967025/242612716-b778d13a-a1f3-4f13-8d8b-360d065653b3.png)

说实话，改完后
![image](https://github.com/adams549659584/go-proxy-bingai/assets/55913486/3e17c9bf-ce51-4f65-8dbe-9c96e997cf27)
这块没变。。。
我也搞不清楚到底是有没有用

**Comment by ghhuang482** [comment]
也是支持这个改变

**Comment by 008exe** [comment]
建议大佬更新到环境变量里支持自定义

**Comment by shentong0722** [comment]
臣附议

**Comment by SokWith** [comment]
> > 感觉是这个 ![image](https://user-images.githubusercontent.com/129967025/242612716-b778d13a-a1f3-4f13-8d8b-360d065653b3.png)
> 
> 说实话，改完后 ![image](https://user-images.githubusercontent.com/55913486/242643675-3e17c9bf-ce51-4f65-8dbe-9c96e997cf27.png) 这块没变。。。 我也搞不清楚到底是有没有用

 试了一下，改了下面这2个地方后，服务器选择就换了地址，并自动加上了自定义地址：

![image](https://github.com/adams549659584/go-proxy-bingai/assets/129967025/c6877da0-3cc9-4ffa-ba33-c73ba825bd95)


![image](https://github.com/adams549659584/go-proxy-bingai/assets/129967025/44f0e398-d7bf-4d1b-9127-6efdec39cb09)

可能一个是源码，一个是编译后的，结果如下：

![image](https://github.com/adams549659584/go-proxy-bingai/assets/129967025/d12e1cb5-e0d2-46bb-ade8-97f42be26bfb)

**Comment by Nothingness-Void** [comment]
> > > 感觉是这个 ![image](https://user-images.githubusercontent.com/129967025/242612716-b778d13a-a1f3-4f13-8d8b-360d065653b3.png)
> > 
> > 
> > 说实话，改完后 ![image](https://user-images.githubusercontent.com/55913486/242643675-3e17c9bf-ce51-4f65-8dbe-9c96e997cf27.png) 这块没变。。。 我也搞不清楚到底是有没有用
> 
> 试了一下，改了下面这2个地方后，服务器选择就换了地址，并自动加上了自定义地址：
> 
> ![image](https://user-images.githubusercontent.com/129967025/242915932-c6877da0-3cc9-4ffa-ba33-c73ba825bd95.png)
> 
> ![image](https://user-images.githubusercontent.com/129967025/242914178-44f0e398-d7bf-4d1b-9127-6efdec39cb09.png)
> 
> 可能一个是源码，一个是编译后的，结果如下：
> 
> ![image](https://user-images.githubusercontent.com/129967025/242913169-d12e1cb5-e0d2-46bb-ade8-97f42be26bfb.png)
> 
> 注意：要清除浏览器的缓存后才生效

改完了，感谢
