### ISSUE TITLE
填写cookie后一发送消息就报错： 无效域。如果此问题仍然存在，请与站点管理员联系。

### ISSUE THREAD

**Issue by rakaki** [adams549659584/go-proxy-bingai#136]
![image](https://github.com/adams549659584/go-proxy-bingai/assets/88972415/7069d650-6d86-4186-b4ef-041714cf3af4)
控制台报错如下：
![image](https://github.com/adams549659584/go-proxy-bingai/assets/88972415/1e231c8c-24c0-4583-bb67-602902e50b34)
v1?ray=7d0c59de6ce915d2:1 
        
POST https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/g/flow/ov1/1082685781:1685671582:siLFTzHJyA79_7A6A9ItdCHmgqB97ZVB4mkp4G87imo/7d0c59de6ce915d2/9220b3553a7dc43 403
fB.<computed> @ v1?ray=7d0c59de6ce915d2:1
setTimeout(异步)
(匿名) @ v1?ray=7d0c59de6ce915d2:1
bahia @ v1?ray=7d0c59de6ce915d2:1
fH @ v1?ray=7d0c59de6ce915d2:1
fB.<computed> @ v1?ray=7d0c59de6ce915d2:1
(匿名) @ v1?ray=7d0c59de6ce915d2:1
api.js:1  [Cloudflare Turnstile] invalid_domain.
u @ api.js:1
z @ api.js:1
api.js:1  Uncaught Error: [Cloudflare Turnstile] invalid_domain.
    at u (api.js:1:2896)
    at z (api.js:1:11758)

不填写cookie的话可以正常使用。

**Comment by xx791117** [comment]
同问！郁闷坏了 
![image](https://github.com/adams549659584/go-proxy-bingai/assets/17248041/e923adf5-8643-4beb-a577-235b110488ee)

**Comment by rakaki** [comment]
都是自己用的号，试了两个号都是这样。去官网验证就是指直接魔法上网去new bing页面吗？

**Comment by xx791117** [comment]
> 都是自己用的号，试了两个号都是这样。去官网验证就是指直接魔法上网去new bing页面吗？

同问 我试了半天把bing退了重新登陆好像也不行 ，要怎么去官网通过验证啊 ？

**Comment by xx791117** [comment]
> 都是自己用的号，试了两个号都是这样。去官网验证就是指直接魔法上网去new bing页面吗？

明白了哥们儿，要在微软官方的bing上聊一下天 他就验证了 ，验证后你把bing的聊天关了 再用自己的服务器和cooki就可以正常了 
![image](https://github.com/adams549659584/go-proxy-bingai/assets/17248041/ff1226ba-032b-441a-be2c-e700ff4affbb)

**Comment by rakaki** [comment]
好的，多谢
