### ISSUE TITLE
使用Cookie设置用户后，无法正常聊天

### ISSUE THREAD

**Issue by Winnie0408** [adams549659584/go-proxy-bingai#141]
不使用Cookie，直接与Bing聊天，可以正常对话；
复制Cookie中_U的值，粘贴到 设置用户 对话框，保存，并点击扫把按钮重置对话：
**无论发送什么，都一直提示“很抱歉，似乎出现错误。让我们重新开始吧。”**
**但画图可用。**
![image](https://github.com/adams549659584/go-proxy-bingai/assets/42741874/15680aec-7b77-41aa-b31e-65044dcffa8a)

![image](https://github.com/adams549659584/go-proxy-bingai/assets/42741874/6a480533-dff8-4874-9de3-40ae3d86f9c2)

**Comment by adams549659584** [comment]
看看浏览器控制台有没有报错，自己部署的话，需要 https 和 域名的

**Comment by yincangshiwei** [comment]
> 看看浏览器控制台有没有报错，自己部署的话，需要 https 和 域名的
我也是，已经是https和域名状态了。只有绘画可用，控制台也没有报错。

**Comment by yincangshiwei** [comment]
> 看看浏览器控制台有没有报错，自己部署的话，需要 https 和 域名的

只有绘画可用

**Comment by Winnie0408** [comment]
> 看看浏览器控制台有没有报错，自己部署的话，需要 https 和 域名的

通过nginx，使用了HTTPS，并绑定了域名，未登录状态可以正常聊天；只要输入了_U的值，就无法聊天。
换用Railway部署，输入同样的_U值，可以正常聊天。

**Comment by polarisaspire** [comment]
我也遇到了同样的问题，请问有进展吗

**Comment by Winnie0408** [comment]
> 我也遇到了同样的问题，请问有进展吗

暂时还没有呢😭😭😭

可以先用其他的在线部署，比如README中介绍的Railway等，实测用cookie设置用户后，可以正常聊天
(但是Railway国内不能直接访问😂😂😂)

**Comment by polarisaspire** [comment]
map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}


server {
  listen 443 ssl;
  server_name bing.xxx.com;

  ssl_certificate xxxx.crt; # 证书地址
  ssl_certificate_key xxxxx.key; # 秘钥地址

 location / {
    proxy_pass http://127.0.0.1:8080;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Port $server_port;
  }
}

nginx配置没写对，改一下就可以了，针对ws做一下区分

**Comment by Winnie0408** [comment]
> map $http_upgrade $connection_upgrade {
>   default upgrade;
>   ''      close;
> }
> 
> 
> server {
>   listen 443 ssl;
>   server_name bing.xxx.com;
> 
>   ssl_certificate xxxx.crt; # 证书地址
>   ssl_certificate_key xxxxx.key; # 秘钥地址
> 
>  location / {
>     proxy_pass http://127.0.0.1:8080;
>     proxy_http_version 1.1;
>     proxy_set_header Upgrade $http_upgrade;
>     proxy_set_header Connection $connection_upgrade;
>     proxy_set_header Host $host;
>     proxy_set_header X-Forwarded-Proto $scheme;
>     proxy_set_header X-Forwarded-Host $host;
>     proxy_set_header X-Forwarded-Port $server_port;
>   }
> }
> 
> nginx配置没写对，改一下就可以了，针对ws做一下区分

还是不行😂😂😂
但是现在不提示“让我们重新开始”了，而是卡在“正在尝试连接，请稍候”，刷新网页也还是显示这个😐😐😐

**Comment by polarisaspire** [comment]
> > map $http_upgrade $connection_upgrade {
> > default upgrade;
> > ''      close;
> > }
> > server {
> > listen 443 ssl;
> > server_name bing.xxx.com;
> > ssl_certificate xxxx.crt; # 证书地址
> > ssl_certificate_key xxxxx.key; # 秘钥地址
> > location / {
> > proxy_pass http://127.0.0.1:8080;
> > proxy_http_version 1.1;
> > proxy_set_header Upgrade $http_upgrade;
> > proxy_set_header Connection $connection_upgrade;
> > proxy_set_header Host $host;
> > proxy_set_header X-Forwarded-Proto $scheme;
> > proxy_set_header X-Forwarded-Host $host;
> > proxy_set_header X-Forwarded-Port $server_port;
> > }
> > }
> > nginx配置没写对，改一下就可以了，针对ws做一下区分
> 
> 还是不行😂😂😂 但是现在不提示“让我们重新开始”了，而是卡在“正在尝试连接，请稍候”，刷新网页也还是显示这个😐😐😐

这就不知道的，反正我的ok了

**Comment by yincangshiwei** [comment]
> > > map $http_upgrade $connection_upgrade {
> > > default upgrade;
> > > ''      close;
> > > }
> > > server {
> > > listen 443 ssl;
> > > server_name bing.xxx.com;
> > > ssl_certificate xxxx.crt; # 证书地址
> > > ssl_certificate_key xxxxx.key; # 秘钥地址
> > > location / {
> > > proxy_pass http://127.0.0.1:8080;
> > > proxy_http_version 1.1;
> > > proxy_set_header Upgrade $http_upgrade;
> > > proxy_set_header Connection $connection_upgrade;
> > > proxy_set_header Host $host;
> > > proxy_set_header X-Forwarded-Proto $scheme;
> > > proxy_set_header X-Forwarded-Host $host;
> > > proxy_set_header X-Forwarded-Port $server_port;
> > > }
> > > }
> > > nginx配置没写对，改一下就可以了，针对ws做一下区分
> > 
> > 
> > 还是不行😂😂😂 但是现在不提示“让我们重新开始”了，而是卡在“正在尝试连接，请稍候”，刷新网页也还是显示这个😐😐😐
> 
> 这就不知道的，反正我的ok了

我用云函数没有nginx

**Comment by Winnie0408** [comment]
> > > > map $http_upgrade $connection_upgrade {
> > > > default upgrade;
> > > > ''      close;
> > > > }
> > > > server {
> > > > listen 443 ssl;
> > > > server_name bing.xxx.com;
> > > > ssl_certificate xxxx.crt; # 证书地址
> > > > ssl_certificate_key xxxxx.key; # 秘钥地址
> > > > location / {
> > > > proxy_pass http://127.0.0.1:8080;
> > > > proxy_http_version 1.1;
> > > > proxy_set_header Upgrade $http_upgrade;
> > > > proxy_set_header Connection $connection_upgrade;
> > > > proxy_set_header Host $host;
> > > > proxy_set_header X-Forwarded-Proto $scheme;
> > > > proxy_set_header X-Forwarded-Host $host;
> > > > proxy_set_header X-Forwarded-Port $server_port;
> > > > }
> > > > }
> > > > nginx配置没写对，改一下就可以了，针对ws做一下区分
> > > 
> > > 
> > > 还是不行😂😂😂 但是现在不提示“让我们重新开始”了，而是卡在“正在尝试连接，请稍候”，刷新网页也还是显示这个😐😐😐
> > 
> > 这就不知道的，反正我的ok了
> 
> 我用云函数没有nginx

本地部署才要用nginx来反向代理，套个https

**Comment by fanrengyiping** [comment]
这种情况可能是由于Cookie值不正确或已过期导致的。请确保您复制的是当前有效的Cookie值，并且在设置用户对话框中正确地粘贴了该值。如果Cookie值已过期，则需要更新Cookie值。

另外，有时候Bing聊天会出现一些临时的问题，导致无法正常工作。您可以尝试重新启动应用程序或稍后再尝试。

如果问题仍然存在，请尝试清除浏览器缓存和Cookie，然后重新登录并再次尝试。如果问题仍然无法解决，请联系Bing聊天的技术支持团队进行进一步的帮助。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Harry-zklcdc** [comment]
已修复，https://github.com/adams549659584/go-proxy-bingai/issues/282
