### ISSUE TITLE
希望docker部署的go-proxy-bingai能够支持设置默认聊天服务器

### ISSUE THREAD

**Issue by Steve5wutongyu6** [adams549659584/go-proxy-bingai#145]
希望能增加通过环境变量指定默认聊天服务器的功能，以方便通过docker部署该应用的用户方便使用
![image](https://github.com/adams549659584/go-proxy-bingai/assets/77491648/241d8406-dc01-4c53-bf71-05067e66350f)
![image](https://github.com/adams549659584/go-proxy-bingai/assets/77491648/49907caf-04f3-4f7e-a233-bb2ad4425d8e)

**Comment by adams549659584** [comment]
首次使用会弹出聊天服务器选择的，选择后，后续不清理都不用再选，后续有空再改了。

**Comment by Steve5wutongyu6** [comment]
好的
