### ISSUE TITLE
请问下，cookie的有效期是多久？

### ISSUE THREAD

**Issue by justincnn** [adams549659584/go-proxy-bingai#150]
同一个cookie会用在不同的设备，比如手机浏览器，和不同电脑的浏览器，

不定期的提示cookie到期，这个cookie的有效期是多久？

**Comment by rock0505** [comment]
可以使用浏览器的开发人员工具来查看网页的HTTP Cookie。例如，在Microsoft Edge中，右键单击页面，然后选择“检查”或按F12,单击“应用程序”选项卡以打开“应用程序”工具。在“存储”下，展开“Cookie”，然后选择一个源。Cookie表包含以下字段：名称、值、域、路径、过期/最大期限等。其中，过期/最大期限字段表示Cookie的到期日期或最长期限。
