### ISSUE TITLE
vercel + cloudflare部署，重定向次数过多

### ISSUE THREAD

**Issue by cyist** [adams549659584/go-proxy-bingai#156]
![image](https://github.com/adams549659584/go-proxy-bingai/assets/62378385/21ceb217-a93c-491b-9f35-20ab56075001)
![image](https://github.com/adams549659584/go-proxy-bingai/assets/62378385/e6bc9ff5-7789-42aa-a0ca-210cffe6d43e)
![image](https://github.com/adams549659584/go-proxy-bingai/assets/62378385/ecb178ea-27da-4cb9-b0d7-bda72020eeb9)
![image](https://github.com/adams549659584/go-proxy-bingai/assets/62378385/1745a8c7-85e2-4aeb-8e37-c092a1b25ad0)
如图，CNAME、workers、CF代理、DNS都配置好了，但是访问显示重定向次数过多

**Comment by fangxy926** [comment]
需要调整SSL/TSL加密模式为 **完全**
![图片](https://github.com/adams549659584/go-proxy-bingai/assets/23739775/89a4e5fe-0192-41bf-b2f5-364489a778cf)
