### ISSUE TITLE
在自己的服务器上使用docker部属完这个项目之后，使用服务器ip地址:8080访问一只在跳三个点，配置nginx反向代理后网页502无法访问

### ISSUE THREAD

**Issue by oldtian123** [adams549659584/go-proxy-bingai#162]
如标题所述，使用服务器自己的ip地址:8080访问就是一只循环那三个点
![屏幕截图 2023-06-05 111027](https://github.com/adams549659584/go-proxy-bingai/assets/92254396/4f2b4d9e-73b1-4003-9e21-4ea35ade6de1)
使用nginx proxy manager配置完nginx反向代理后，使用配置的ip地址直接出现502页面
![屏幕截图 2023-06-05 111249](https://github.com/adams549659584/go-proxy-bingai/assets/92254396/5b276218-7463-4dd0-8f21-cb337fa5c0d8)
下面是nginx配置
![屏幕截图 2023-06-05 112121](https://github.com/adams549659584/go-proxy-bingai/assets/92254396/6296dfc1-6db1-4232-993b-aba441d2d6c8)
ssl证书打开，其他均没有配置
试了很多办法但是不知道什么原因导致的，有没有人知道什么问题

**Comment by oldtian123** [comment]
忘了说了，服务器是非大陆服务器，可以正常访问newbing的网页服务

**Comment by Li-Qifeng** [comment]
如果是docker部署的话，转发主机ip要填docker的宿主ip，(可以用 ip add show docker0 查询到IP)，配置好重启一下bing那个docker
