### ISSUE TITLE
非常棒的项目，适合部署给家人朋友用

### ISSUE THREAD

**Issue by mwnu** [adams549659584/go-proxy-bingai#18]
要是能够在服务端配置Cookie和前端访问的账号密码就更好了。

**Comment by adams549659584** [comment]
后续应该会加下简单的授权控制，服务端配置 Cookie 多人使用的话，很快就会触发验证码和达到24小时限制了，后续可以考虑加回去试试

**Comment by mwnu** [comment]
> 后续应该会加下简单的授权控制，服务端配置 Cookie 多人使用的话，很快就会触发验证码和达到24小时限制了，后续可以考虑加回去试试

或许可以搞个bing的cookie市场，自动更新到自托管的服务端，目前中文AI网页搜索体验bing无可替代，加上免费、可以绘图，还将推出插件市场。

**Comment by adams549659584** [comment]
配置文件简单加下算了，太多账号申请也挺麻烦的，不过共用账号，其实聊天历史也就共用了。

**Comment by adams549659584** [comment]
是的，手机版不显示的，微软自带的逻辑来的，手机版位不够吧

**Comment by mwnu** [comment]
> 是的，手机版不显示的，微软自带的逻辑来的，手机版位不够吧

这个历史记录看上去是跟微软账号绑定的，能同步到其他客户端，这样的话就不适合分享给多人使用了，好在不使用cookie也能搜索，只不过不能文生图了。

**Comment by adams549659584** [comment]
是的，不过历史记录是可以配置关闭的

**Comment by adams549659584** [comment]
![image](https://github.com/adams549659584/go-proxy-bingai/assets/10492939/22e07391-5315-4e0b-b3c1-9e8c53492c65)
可以直接配置 config.js 的 enableThreads 为 0 就可以

**Comment by mwnu** [comment]
> config.js

这个得自己构建Docker镜像吗？我没有映射文件路径/
