### ISSUE TITLE
能否支持选择语言

### ISSUE THREAD

**Issue by ErlendLee** [adams549659584/go-proxy-bingai#19]
中文的语料库一般只有知乎和百度知道这些，有些搜索质量比较差。能否通过设置指定使用英文搜索。

**Comment by adams549659584** [comment]
暂时没发现怎样设置，大概只能使用对话中限定下

**Comment by ErlendLee** [comment]
> 暂时没发现怎样设置，大概只能使用对话中限定下

嗯，谢谢。
很赞的项目，感谢大佬！
