### ISSUE TITLE
无法查看和导出记录，GetConversation请求失败

### ISSUE THREAD

**Issue by msyzzm** [adams549659584/go-proxy-bingai#193]
下面是查看网络请求的记录

请求 URL:
https://XXX/sydney/GetConversation?conversationId=51D%7CBingProdUnAuthenticatedUsers%7C576D1F89B87DEF35FAD0554F0CC2F4CF013CA5F2B8C4727DDD59B5772E13BA4B&source=cib
请求方法:
GET
状态代码:
401

**Comment by adams549659584** [comment]
#160

**Comment by msyzzm** [comment]
感谢回复！
