### ISSUE TITLE
服务选择内“本站”不可用（搞很久了希望大佬帮助一下）

### ISSUE THREAD

**Issue by richardlzs** [adams549659584/go-proxy-bingai#195]
请问要"本站"选项能够工作，具体需要如何配置？
是需要配置特定的环境变量?
还是需要nginx将本站根目录的流量转发到cloudflare的聊天服务器上？

使用版本：release 1.8.7

目前直接在服务选择里面输入自定义的聊天服务器网址是能够工作的，但为了方便还是希望能够直接能点一个选项就连上。

**Comment by adams549659584** [comment]
如果 docker 部署，配置参考下 #71 ，用 nginx 的话需要配置下 ws 的路径

**Comment by richardlzs** [comment]
我是直接在linux上面直接运行解压之后的release版本的，能具体说说ws的路径要怎么配置吗。是将 location /sydney/ChatHub 的块直接proxy_pass到cloudflare聊天服务器吗(我目前是这样做的，似乎不行)

附带上我目前location /sydney/ChatHub的配置
        location /sydney/ChatHub {
    proxy_pass https://我的聊天服务器的域名;
    proxy_http_version                 1.1;
    proxy_set_header Upgrade           $http_upgrade;
    #proxy_set_header Connection        $connection_upgrade;#此行nginx版本过低不识别，是这个问题吗？
    proxy_set_header Host              $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host  $host;
    proxy_set_header X-Forwarded-Port  $server_port;
}

**Comment by gevikhn** [comment]
我时这样配置的nginx，聊天服务器可以选择本站，8080是聊天服务器，使用docker部署的
```
location /sydney/ChatHub {
              proxy_pass http://172.17.0.1:8080;
              proxy_http_version                 1.1;
              proxy_set_header Upgrade           $http_upgrade;
              proxy_set_header Connection        $connection_upgrade;
              proxy_set_header Host              $host;
              proxy_set_header X-Forwarded-Proto $scheme;
              proxy_set_header X-Forwarded-Host  $host;
              proxy_set_header X-Forwarded-Port  $server_port;
        }

        location / {
                proxy_pass http://172.17.0.1:8080;

                proxy_redirect  http:// https://;
                proxy_set_header Host              $host:$server_port;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Host  $host;
                proxy_set_header X-Forwarded-Port  $server_port;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location ~ .*\.(js|css|jpg|jpeg|gif|png|ico|pdf|txt)$ {
                proxy_pass http://172.17.0.1:8080;

                proxy_set_header Host              $host:$server_port;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Host  $host;
                proxy_set_header X-Forwarded-Port  $server_port;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
```

**Comment by billysingo** [comment]
> 我是直接在linux上面直接运行解压之后的release版本的，能具体说说ws的路径要怎么配置吗。是将 location /sydney/ChatHub 的块直接proxy_pass到cloudflare聊天服务器吗(我目前是这样做的，似乎不行)
> 
> 附带上我目前location /sydney/ChatHub的配置 location /sydney/ChatHub { proxy_pass [https://我的聊天服务器的域名](https://%E6%88%91%E7%9A%84%E8%81%8A%E5%A4%A9%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%9A%84%E5%9F%9F%E5%90%8D); proxy_http_version 1.1; proxy_set_header Upgrade $http_upgrade; #proxy_set_header Connection $connection_upgrade;#此行nginx版本过低不识别，是这个问题吗？ proxy_set_header Host $host; proxy_set_header X-Forwarded-Proto $scheme; proxy_set_header X-Forwarded-Host $host; proxy_set_header X-Forwarded-Port $server_port; }

老版本就用   proxy_set_header Connection    "upgrade";

**Comment by fanrengyiping** [comment]
看起来您已经配置了Nginx，以便代理将请求传递到在端口8080上运行的ChatHub服务器。您还配置了Nginx，以便将静态文件（js、css、图像等）的请求代理传递到同一个ChatHub服务器。此外，您还设置了必要的标头以使代理传递正常工作。您有什么需要帮助的吗？

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by richardlzs** [comment]
谢谢各位大佬

**Comment by kanglehao** [comment]
> 我时这样配置的nginx，聊天服务器可以选择本站，8080是聊天服务器，使用docker部署的
> 
> ```
> location /sydney/ChatHub {
>               proxy_pass http://172.17.0.1:8080;
>               proxy_http_version                 1.1;
>               proxy_set_header Upgrade           $http_upgrade;
>               proxy_set_header Connection        $connection_upgrade;
>               proxy_set_header Host              $host;
>               proxy_set_header X-Forwarded-Proto $scheme;
>               proxy_set_header X-Forwarded-Host  $host;
>               proxy_set_header X-Forwarded-Port  $server_port;
>         }
> 
>         location / {
>                 proxy_pass http://172.17.0.1:8080;
> 
>                 proxy_redirect  http:// https://;
>                 proxy_set_header Host              $host:$server_port;
>                 proxy_set_header X-Forwarded-Proto $scheme;
>                 proxy_set_header X-Forwarded-Host  $host;
>                 proxy_set_header X-Forwarded-Port  $server_port;
>                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         }
>         location ~ .*\.(js|css|jpg|jpeg|gif|png|ico|pdf|txt)$ {
>                 proxy_pass http://172.17.0.1:8080;
> 
>                 proxy_set_header Host              $host:$server_port;
>                 proxy_set_header X-Forwarded-Proto $scheme;
>                 proxy_set_header X-Forwarded-Host  $host;
>                 proxy_set_header X-Forwarded-Port  $server_port;
>                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>             }
> ```

这个可行,解决了~我原来的配置是 
location / {
 proxy_pass http://127.0.0.1:8080/;
 rewrite ^/(.*)$ /$1 break;
 proxy_redirect off;
 proxy_set_header Host $host;
 proxy_set_header X-Forwarded-Proto $scheme;
 proxy_set_header X-Real-IP $remote_addr;
 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
 proxy_set_header Upgrade-Insecure-Requests 1;
 proxy_set_header X-Forwarded-Proto https;
}

**Comment by Nothingness-Void** [comment]
> 我时这样配置的nginx，聊天服务器可以选择本站，8080是聊天服务器，使用docker部署的
> 
> ```
> location /sydney/ChatHub {
>               proxy_pass http://172.17.0.1:8080;
>               proxy_http_version                 1.1;
>               proxy_set_header Upgrade           $http_upgrade;
>               proxy_set_header Connection        $connection_upgrade;
>               proxy_set_header Host              $host;
>               proxy_set_header X-Forwarded-Proto $scheme;
>               proxy_set_header X-Forwarded-Host  $host;
>               proxy_set_header X-Forwarded-Port  $server_port;
>         }
> 
>         location / {
>                 proxy_pass http://172.17.0.1:8080;
> 
>                 proxy_redirect  http:// https://;
>                 proxy_set_header Host              $host:$server_port;
>                 proxy_set_header X-Forwarded-Proto $scheme;
>                 proxy_set_header X-Forwarded-Host  $host;
>                 proxy_set_header X-Forwarded-Port  $server_port;
>                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         }
>         location ~ .*\.(js|css|jpg|jpeg|gif|png|ico|pdf|txt)$ {
>                 proxy_pass http://172.17.0.1:8080;
> 
>                 proxy_set_header Host              $host:$server_port;
>                 proxy_set_header X-Forwarded-Proto $scheme;
>                 proxy_set_header X-Forwarded-Host  $host;
>                 proxy_set_header X-Forwarded-Port  $server_port;
>                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>             }
> ```

我在windows部署，完全照搬这个nginx配置但是本站依然不可用，linux正常
