### ISSUE TITLE
侧边栏添加当前页面灰色

### ISSUE THREAD

**Issue by Exception-H** [adams549659584/go-proxy-bingai#197]
撰写页面可以正常添加, 但聊天页面的添加按钮是灰色的
![图片编辑_20230609105208](https://github.com/adams549659584/go-proxy-bingai/assets/53857463/71c5b1e3-1dd9-4085-9408-5634c14561a5)

**Comment by chenweiask** [comment]
我跟你正好相反。我添加聊天页面可以的，但是添加撰写是灰色。

**Comment by Exception-H** [comment]
> 我跟你正好相反。我添加聊天页面可以的，但是添加撰写是灰色。

应该是域名相同的问题
