### ISSUE TITLE
同一网络环境下win能正常打开页面，Linux却不能

### ISSUE THREAD

**Issue by ikenxuan** [adams549659584/go-proxy-bingai#2]
同网络环境，都没有使用代理服务。在使用.exe可以正常访问，但是在centos7上运行后页面显示不完全，并且弹出如下报错
![02](https://user-images.githubusercontent.com/112480306/236502633-fd082a4e-0afd-4dc6-9e78-d871b2bad541.png)

**Comment by adams549659584** [comment]
这个一般是访问不了www.bing.com，超时取消了。部署的话，是需要能访问 www.bing.com 的服务器的

**Comment by ikenxuan** [comment]
ok好的谢谢
