### ISSUE TITLE
Render封仓事故，其实大家没必要自己再建前端服务器

### ISSUE THREAD

**Issue by SokWith** [adams549659584/go-proxy-bingai#203]
只在cf上建后端聊天服务器，保证自己的使用次数足够。
前端就直接撸项目作者的甲骨文小鸡仔就好了

**Comment by riverai** [comment]
还没开始部署。你的意思是说，cf上的部署代码完全是自己的后端，其他的前端套壳这个后端就可以了是吗？
而docker部署，是完整的前后端一起自己部署自己的，更麻烦的意思吗？

**Comment by riverai** [comment]
用起来了，这个方法的确不错，最最省事，3分钟搞定。
