### ISSUE TITLE
实现有问题，不能新建聊天，画图不显示

### ISSUE THREAD

**Issue by luowei729** [adams549659584/go-proxy-bingai#21]
使用默认cookies
![image](https://github.com/adams549659584/go-proxy-bingai/assets/10611605/3f202694-99cc-4e32-bbe1-5dfd3e1de6e7)
![image](https://github.com/adams549659584/go-proxy-bingai/assets/10611605/9035022b-33c5-4ea9-a54c-20884c8b28d6)

**Comment by lwd-temp** [comment]
应该没有“默认cookie”，默认是未登录状态，应该是不能画图的。

**Comment by adams549659584** [comment]
新建聊天是左下角的新主题，登录用户的聊天记录是在线同步的，未登录用户的刷新会丢失，我看看未登录的要不屏蔽好了

**Comment by mwnu** [comment]
是你网络问题，我之前也碰到过，选一个稳定的节点。

**Comment by justabc1** [comment]
请教一下，16.8版本正常可以聊天，但是用cookie登录之后，还是没办法画图（使用人搭建的演示站点却可以画图），这是为什么呀

**Comment by adams549659584** [comment]
/images/create?re=1&showselective=1&sude=1&kseed=7500&SFX=2&q=

> 请教一下，16.8版本正常可以聊天，但是用cookie登录之后，还是没办法画图（使用人搭建的演示站点却可以画图），这是为什么呀

你可以在浏览器 F12 或 Ctrl + Shift + i 打开开发者模式看看，让 bing 画图的时候，接口是怎样的状态，也可以直接试试访问画图接口 ：你的域名/images/create?re=1&showselective=1&sude=1&kseed=7500&SFX=2&q=小熊猫

**Comment by justabc1** [comment]
直接让他画的时候，会显示文字“好的，我会尽力画一只小熊猫给你看”，然后就会显示正在响应中3秒左右，但是没有图片出现也没有方框出现就结束了。状态代码好像一直是200。


如果是访问你说的那个画图网址的画是全空白画面

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月20日(周六) 凌晨0:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [adams549659584/go-proxy-bingai] 实现有问题，不能新建聊天，画图不显示 (Issue #21)




 
/images/create?re=1&amp;showselective=1&amp;sude=1&amp;kseed=7500&amp;SFX=2&amp;q=
  
请教一下，16.8版本正常可以聊天，但是用cookie登录之后，还是没办法画图（使用人搭建的演示站点却可以画图），这是为什么呀
  
你可以在浏览器 F12 或 Ctrl + Shift + i 打开开发者模式看看，让 bing 画图的时候，接口是怎样的状态，也可以直接试试访问画图接口 ：你的域名/images/create?re=1&amp;showselective=1&amp;sude=1&amp;kseed=7500&amp;SFX=2&amp;q=小熊猫

**Comment by justabc1** [comment]
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月20日(周六) 凌晨0:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [adams549659584/go-proxy-bingai] 实现有问题，不能新建聊天，画图不显示 (Issue #21)




 
/images/create?re=1&amp;showselective=1&amp;sude=1&amp;kseed=7500&amp;SFX=2&amp;q=
  
请教一下，16.8版本正常可以聊天，但是用cookie登录之后，还是没办法画图（使用人搭建的演示站点却可以画图），这是为什么呀
  
你可以在浏览器 F12 或 Ctrl + Shift + i 打开开发者模式看看，让 bing 画图的时候，接口是怎样的状态，也可以直接试试访问画图接口 ：你的域名/images/create?re=1&amp;showselective=1&amp;sude=1&amp;kseed=7500&amp;SFX=2&amp;q=小熊猫
