### ISSUE TITLE
无法画图

### ISSUE THREAD

**Issue by forczc** [adams549659584/go-proxy-bingai#22]
1. 默认cookie，自己部署的站点（有代理）
2. 手动加cookie，自己部署的站点
3. 手动加cookie，用作者提供的案例站点
4. 重新退出bing登陆再重新登录，获取新的cookie

以上都尝试过，均无法画图

如图最终301到这个url好像就停了：
![image](https://github.com/adams549659584/go-proxy-bingai/assets/13718643/04d099f6-f60d-4bfd-b8c8-e636bd8098b3)

**Comment by adams549659584** [comment]
这边登录后尝试，会有两次302，最后一次200，然后出图的
![image](https://github.com/adams549659584/go-proxy-bingai/assets/10492939/a52c4c14-a74f-41b2-af2b-1d2afeb5e5f0)
![image](https://github.com/adams549659584/go-proxy-bingai/assets/10492939/03cbfaf7-33b0-44a6-8e23-47a7875c347c)
![image](https://github.com/adams549659584/go-proxy-bingai/assets/10492939/f34c775f-43e6-46e8-973d-f46f02cf0c70)

**Comment by forczc** [comment]
> 这边登录后尝试，会有两次302，最后一次200，然后出图的 ![image](https://user-images.githubusercontent.com/10492939/238813786-a52c4c14-a74f-41b2-af2b-1d2afeb5e5f0.png) ![image](https://user-images.githubusercontent.com/10492939/238813850-03cbfaf7-33b0-44a6-8e23-47a7875c347c.png) ![image](https://user-images.githubusercontent.com/10492939/238813913-f34c775f-43e6-46e8-973d-f46f02cf0c70.png)

有点神奇，我用cookie试，第一次301，然后第二次就到了
https://bing.vcanbb.top/images/create?FORM=SYDBIC 这个200的url了，然后就停了，没图出来。
难不成我号有问题？有点懵

**Comment by adams549659584** [comment]
可能是吧，我这边试的基本正常的

**Comment by luowei729** [comment]
> 可能是吧，我这边试的基本正常的

是实现的问题。我有其他项目没有这个问题
