### ISSUE TITLE
linux arm64可执行文件格式错误

### ISSUE THREAD

**Issue by 3dswicks** [adams549659584/go-proxy-bingai#221]
./go-proxy-bingai
bash: ./go-proxy-bingai: cannot execute binary file: Exec format error

不会是版本不对吗？

**Comment by Winnie0408** [comment]
好像的确有问题，不过可以直接用go跑main.go，或者用go自行编译
先`git clone仓库`
然后`sudo apt-get install golang`安装go
`cd`进项目目录，`go run main.go`就行
或者`go build main.go`，编译成可执行文件

如果go下载依赖包比较慢，可以换个源
`go env -w GOPROXY=https://goproxy.cn,direct`
然后重新`go run main.go`或者`go build main.go`

**Comment by Declarcall** [comment]
我 arm Ubuntu 20.04 上也出现同样的问题

**Comment by jachaussloef** [comment]
因为arm64版本给的是x86-64的二进制文件
`file go-proxy-bingai
go-proxy-bingai: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=V7mx1wz5ytnHt-Re6NtO/xl4ZQb3xCvzapU7-xEXJ/g2qj2XpGUehPgnbu34Bk/pt8TU5cH6m-wRBbWypyB, stripped`

**Comment by 3dswicks** [comment]
我重新编译了一下arm版本，可以运行了，但是web页面还是打不开，有成功的吗？
