### ISSUE TITLE
使用代理访问的时候，会出现404，无法使用

### ISSUE THREAD

**Issue by wintrue** [adams549659584/go-proxy-bingai#23]
使用代理访问的时候，会出现404，无法使用，是不是实现有问题，使用代理的时候会覆盖相关ip配置？还是header头信息多带了什么东西？
![image](https://github.com/adams549659584/go-proxy-bingai/assets/6380530/68401fe9-6b94-4c0e-8bd5-f689e9c70042)
去掉代理vpn就正常，vpn是香港的，香港地区还没开放

**Comment by adams549659584** [comment]
应该是只是代理的问题，dns 走的缓存没更新吧

**Comment by wintrue** [comment]
/turing/captcha/create  访问这个接口，是不是验证，但没实现？

**Comment by adams549659584** [comment]
是验证，基本都是直接代理到微软那的，cloudflare的验证过不了，其他的还没试过

**Comment by adams549659584** [comment]
![image](https://github.com/adams549659584/go-proxy-bingai/assets/10492939/fb2cf36a-bf06-4336-bf2a-1e2887d4362b)
去微软官网看了下，这个也是还没有的
