### ISSUE TITLE
我在Railway中部署了，然后将自己的域名绑定上去，railway中显示成功，但是访问时一直重定向错误

### ISSUE THREAD

**Issue by Hanzo-Huang** [adams549659584/go-proxy-bingai#232]

**Comment by Hanzo-Huang** [comment]
我在Railway中部署了，然后将自己的域名绑定上去，railway中显示成功，但是访问时一直重定向错误。”redirected you too many times.“

**Comment by byte-hzzh** [comment]
[](url)
![屏幕截图 2023-06-17 230139](https://github.com/adams549659584/go-proxy-bingai/assets/55130144/f69765a8-c012-4a90-a4fd-c4b9d638b33d)试试这个设置

**Comment by Hanzo-Huang** [comment]
可以了！！谢谢！！！
