### ISSUE TITLE
【help】    {"errorMessage":"Missing accessToken."}

### ISSUE THREAD

**Issue by justincnn** [adams549659584/go-proxy-bingai#25]
在x86的全新服务器上部署

- 部署在全新的vps上出现如上错误，
~~~
{"errorMessage":"Missing accessToken."}
~~~

- 如果换端口，是不是只要把8080:8080，改为其他任意没占用的端口，还是这个docker指定8080？

- 如果这个docker布置在非美国的vps上，比如日本的ip vps，需要额外美国代理么？

### 还是大神协助，谢谢

**Comment by justincnn** [comment]
> 比如 8888:8080，就是可以把8888端口指向 docker 中的8080了，docker的也可以通过环境变量 PORT 来指定任意端口，不过docker 中的不占用宿主机的，只要能直连 www.bing.com 都可以，不需要指定美国代

谢谢，
那请问Miss token这个是什么错误？谢谢啊

**Comment by adams549659584** [comment]
这个没遇到过，是接口还是哪里提示的？

**Comment by justincnn** [comment]
> 这个没遇到过，是接口还是哪里提示的？

直接在浏览器输入，IP：端口
就出现这个提示

**Comment by adams549659584** [comment]
我再部署了个试试，没发现这样啊，可以截图看看吗

**Comment by justincnn** [comment]
> 我再部署了个试试，没发现这样啊，可以截图看看吗

你好，请看如下截图，打开IP：端口，只有如下显示：
![](https://s3.bmp.ovh/imgs/2023/05/19/0316ced7b7b0ac61.jpg)

**Comment by adams549659584** [comment]
没看出是啥问题，搜了下，好像 go-chatgpt-api 会出现这个错误，你是不是搭建了 go-chatgpt-api，访问错了？
https://github.com/linweiyuan/go-chatgpt-api/issues/17

**Comment by justincnn** [comment]
> 没看出是啥问题，搜了下，好像 go-chatgpt-api 会出现这个错误，你是不是搭建了 go-chatgpt-api，访问错了？ [linweiyuan/go-chatgpt-api#17](https://github.com/linweiyuan/go-chatgpt-api/issues/17)

不会啊，我这个是全新的vps，除了你的docker和1panel管理页面外，没有其他内容的

**Comment by adams549659584** [comment]
> > 没看出是啥问题，搜了下，好像 go-chatgpt-api 会出现这个错误，你是不是搭建了 go-chatgpt-api，访问错了？ [linweiyuan/go-chatgpt-api#17](https://github.com/linweiyuan/go-chatgpt-api/issues/17)
> 
> 不会啊，我这个是全新的vps，除了你的docker和1panel管理页面外，没有其他内容的

那确实帮不上忙了，的确没看出是什么问题，项目也没用到  accessToken 什么的。

**Comment by justincnn** [comment]
> > > 没看出是啥问题，搜了下，好像 go-chatgpt-api 会出现这个错误，你是不是搭建了 go-chatgpt-api，访问错了？ [linweiyuan/go-chatgpt-api#17](https://github.com/linweiyuan/go-chatgpt-api/issues/17)
> > 
> > 
> > 不会啊，我这个是全新的vps，除了你的docker和1panel管理页面外，没有其他内容的
> 
> 那确实帮不上忙了，的确没看出是什么问题，项目也没用到 accessToken 什么的。

好的，谢谢
我等下把vps系统重置下再试试看，

- 另外请问下，可以突破20个对话的限制么?

**Comment by adams549659584** [comment]
> > > > 没看出是啥问题，搜了下，好像 go-chatgpt-api 会出现这个错误，你是不是搭建了 go-chatgpt-api，访问错了？ [linweiyuan/go-chatgpt-api#17](https://github.com/linweiyuan/go-chatgpt-api/issues/17)
> > > 
> > > 
> > > 不会啊，我这个是全新的vps，除了你的docker和1panel管理页面外，没有其他内容的
> > 
> > 
> > 那确实帮不上忙了，的确没看出是什么问题，项目也没用到 accessToken 什么的。
> 
> 好的，谢谢 我等下把vps系统重置下再试试看，
> 
> * 另外请问下，可以突破20个对话的限制么?

暂时不行，发现限制是服务器限制的，虽然可以把新会话id给它，但是就不是同一个上下文了。
