### ISSUE TITLE
网站白茫茫的，看不清

### ISSUE THREAD

**Issue by woshibaipiaogua** [adams549659584/go-proxy-bingai#26]
https://bing.vcanbb.top/  为什么这个网站打开后很多字都是白茫茫的，看不太清楚。

**Comment by justincnn** [comment]
我这边好的啊，为了减少owner的服务器压力，打算自己部署，但是一直不成功，哎

**Comment by IMxingyus** [comment]
> 是电脑还是手机看的？可以提供下机型和截图看看吗？我这边暂时没发现

我猜他使用了一些夜间模式插件，这会导致字体和其他元素变白。

**Comment by adams549659584** [comment]
> > 是电脑还是手机看的？可以提供下机型和截图看看吗？我这边暂时没发现
> 
> 我猜他使用了一些夜间模式插件，这会导致字体和其他元素变白。

嗯，暂时不管了

**Comment by woshibaipiaogua** [comment]
我之前用了护眼类型的插件，打开网站后有些字看不清，关闭后就正常了。>_<
