### ISSUE TITLE
前端脚本报错

### ISSUE THREAD

**Issue by SpartanH7** [adams549659584/go-proxy-bingai#27]
用docker和release文件分别部署了一遍，用nginx做的https反向代理，出现了相同的错误：
![8A99Y2_95U$M_8%DHYBHE9G](https://github.com/adams549659584/go-proxy-bingai/assets/74098117/1081cc00-925c-431b-ba94-57ba94e75824)

页面加载时会有如下错误：
![R1SCC`Y_P%KHR1MG %E}{BO](https://github.com/adams549659584/go-proxy-bingai/assets/74098117/5e9b4970-693a-4d78-a337-49561a924572)
![JJV0 A$KO6R~C1_5D%(DC0G](https://github.com/adams549659584/go-proxy-bingai/assets/74098117/fcac285e-0842-479f-b1e6-520fe6f3809b)

发送消息后也没有发送请求：
![`Q2V`WW0CZVC4 }2M4QXZDA](https://github.com/adams549659584/go-proxy-bingai/assets/74098117/fad3aded-ee9e-4439-860e-fe1518f7571f)

**Comment by adams549659584** [comment]
我项目中似乎没有 content 这个js 啊，这个js路径可以发下看看吗

**Comment by SpartanH7** [comment]
> 
在web目录下，可能是框架自动生成的？然后这个问题只有在我设置了自己的cookie的时候才会出现
![I0QSE7D0WPS9OL5`GL3V CB](https://github.com/adams549659584/go-proxy-bingai/assets/74098117/2af87a41-e710-48d0-8136-9914d015539a)

**Comment by adams549659584** [comment]
![image](https://github.com/adams549659584/go-proxy-bingai/assets/10492939/e0bda7f6-491a-4a3c-b082-428153c6cef9)
web 目录下应该只有这些js的，应该没有 content 开头的

**Comment by adams549659584** [comment]
![image](https://github.com/adams549659584/go-proxy-bingai/assets/10492939/a9ce40da-253d-4dea-a80c-ffd448fe3372)
我也是有登录的，只有这些才对的

**Comment by SpartanH7** [comment]
我检查了一下，发现这个content.js是我装的一个插件的脚本，把插件关掉就没这个报错了
但问题还是没解决，我又试了下，发现即使没有输入cookie，当我点新主题后，也会出现这个问题，现在找不到任何报错，也没有向后端发送请求，唯一的报错是请求cdx/bg-sprite.png会404，但应该不是这个问题，如果你有空的话可以麻烦帮忙看一下吗https://spartanh7.world:8021/
![image](https://github.com/adams549659584/go-proxy-bingai/assets/74098117/9ad2edc0-9794-425f-b1ec-03bb5fd53416)

**Comment by adams549659584** [comment]
![image](https://github.com/adams549659584/go-proxy-bingai/assets/10492939/125f467f-238b-4c36-8700-77f9dadede92)

应该是nginx 反代的问题，服务端取到的 scheme 和 端口不对，我的主站也是nginx 反代的，一般需要加上上面这些的
```nginx
upstream ups-bingai-proxy {
    ip_hash;
    server 127.0.0.1:8888 weight=2;
    server 10.0.0.198:8888 weight=1;
    server 10.0.0.181:8888 weight=3;
}

server {
    listen                  443 ssl http2;
    listen                  [::]:443 ssl http2;
    server_name             bing.vcanbb.top;
    root                    /usr/share/nginx/html;

    # Logging
    access_log             /var/log/nginx/access_bingai.log cloudflare;
    error_log              /var/log/nginx/error_bingai.log warn;

    # SSL
    ssl_certificate         /ssl/vcanbb.top/fullchain.pem;
    ssl_certificate_key     /ssl/vcanbb.top/privkey.pem;
    ssl_trusted_certificate /ssl/vcanbb.top/chain.pem;

    # security
    include                 conf.global/security.conf;

    location / {
        proxy_pass http://ups-bingai-proxy;
        include    conf.global/proxy.conf;
    }


    # additional config
    include conf.global/general.conf;
}
```

> conf.global/proxy.conf
```nginx
proxy_http_version                 1.1;
proxy_cache_bypass                 $http_upgrade;

# Proxy headers
proxy_set_header Upgrade           $http_upgrade;
proxy_set_header Connection        $connection_upgrade;
proxy_set_header Host              $host;
proxy_set_header X-Real-IP         $remote_addr;
proxy_set_header Forwarded         $proxy_add_forwarded;
proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Host  $host;
proxy_set_header X-Forwarded-Port  $server_port;

# Proxy timeouts
proxy_connect_timeout              60s;
proxy_send_timeout                 60s;
proxy_read_timeout                 60s;

proxy_buffers                      256 256k;  
proxy_buffer_size                  256k;
```

**Comment by adams549659584** [comment]
> 再问一句，这个有办法配置统一route前缀吗

暂时不行，/web 开头的是网站的，其他的是微软的，一般分配个单独的二级域名就好

**Comment by yincangshiwei** [comment]
> ```nginx
> X-Forwarded-Port
> ```

请问下，如果没用nginx，可否加3个header，直接在go源码里面？
