### ISSUE TITLE
项目也可在replit部署，更加简便且支持WebSocket

### ISSUE THREAD

**Issue by PaloMiku** [adams549659584/go-proxy-bingai#299]
参考仓库：  
https://github.com/yzsong06/Replit_Go_BingAi/
个人演示站点：  
https://newbing.takagi.icu

**Comment by Aurorainic** [comment]
实测明显比vercel部署方式更快。
（域名托管：Cloudflare，未挂梯）
![image](https://github.com/adams549659584/go-proxy-bingai/assets/88829187/a883cc26-2f85-4e2a-82a9-040fe6d37bd2)

**Comment by PaloMiku** [comment]
https://www.takagi.icu/posts/1c2da2ca.html
个人博客参考文章（懒）

**Comment by fenger7** [comment]
大佬能否支持下，4everland ，这个无限免费流量。https://zhuanlan.zhihu.com/p/401381716

**Comment by PaloMiku** [comment]
> 大佬能否支持下，4everland ，这个无限免费流量。https://zhuanlan.zhihu.com/p/401381716

我用过的，这个需要绑定虚拟钱包账号才能实现每月100G流量，这个我不推荐，主要还是受限于Web3钱包问题

**Comment by fenger7** [comment]
好的，谢谢。

**Comment by PaloMiku** [comment]
> 好的，谢谢。

你看的这篇文章也太远古了，现在的4everland已经没有刚出时候那么好了，现在10g流量不是最大问题，问题是支持的程序很少，连个pnpm都跑不了

**Comment by fenger7** [comment]
好的哈

**Comment by crinfok1030** [comment]
这个很好，已经在用了、谢谢大神。可以增加识别图片吗？

**Comment by PaloMiku** [comment]
> 这个很好，已经在用了、谢谢大神。可以增加识别图片吗？

这个估计你得看作者开发计划了，我这只是提供一种部署方式
