### ISSUE TITLE
怎么使用刷新大法呢？试了一会就各种不回答了。

### ISSUE THREAD

**Issue by likegpt2030** [adams549659584/go-proxy-bingai#3]

**Comment by adams549659584** [comment]
### 浏览器中 Ctrl+shift+R 强制刷新下，新版本加了一键重置各种缓存的按钮了。

![重置](https://github.com/adams549659584/go-proxy-bingai/raw/master/docs/img/bing-login.png)

**Comment by adams549659584** [comment]
未登录的话，获取会话id很不稳定，最好还是登录体验，会稳定很多。

**Comment by likegpt2030** [comment]
嗯嗯，感谢，这版更新后好了，还是重置按钮管用，强制刷新不太管用
