### ISSUE TITLE
绘画失效了吗？

### ISSUE THREAD

**Issue by wjx-wiki** [adams549659584/go-proxy-bingai#31]
pc

chrome

演示站/自部署（railway），均没有效果，其中： https://go-proxy-bingai-production-00c3.railway.app/fd/ls/l 报错：404

**Comment by adams549659584** [comment]
这个是微软的一个日志接口来的，你的似乎整个站点都是404，刚试了，绘画还是可以用的，需要登录，使用更有创造力模式的，不过有时候它回复是不会画出来，你可以再部署好之后，试试下面这个链接，之后我看看加个直接画个的窗口
你的域名/images/create?partner=sydney&re=1&showselective=1&sude=1&kseed=7000&SFX=&q=小狗
