### ISSUE TITLE
想修改一下授权窗口的提示信息，想请大佬指点一下，我对前端一窍不通，找半天也搞不定。。。

### ISSUE THREAD

**Issue by zhangbinhui** [adams549659584/go-proxy-bingai#311]
如图：
![image](https://github.com/adams549659584/go-proxy-bingai/assets/7031406/9916b488-adaa-4780-afc8-0b11c02099d7)
这个授权弹窗的内容，我想修改里面的提示信息和图片

我根据文字信息找到了go-proxy-bingai/frontend/src/views/chat/components/Chat/Chat.vue
里面最底下有一段：
<NResult class="box-border w-11/12 lg:w-[400px] px-4 py-4 bg-white rounded-md" status="403" title="401 未授权">
        <template #footer>
          <NInput class="w-11/12" v-model:value="authKey" type="password" placeholder="请输入授权码" maxlength="60" clearable></NInput>
          <n-button class="mt-4" secondary type="info" :loading="isAuthBtnLoading" @click="auth">授权</n-button>
        </template>
      </NResult>
我改了里面的文字，并且重新打包，不生效。。。

然后又翻了一下issue，看到有大佬提示说要修改web/assets/index-3a8b3b00.js 这个文件的内容，我用文字定位到这里，但是一段混效过的js代码，也不晓得改了有没有用，因为既然是编译出来的，我应该去改源头，而不是编译之后的结果，对吗？
希望得到大佬的指点。

be("footer",null,[G(Ev),P.value?(te(),Se("div",Dv,[G(E(ap),{class:"box-border w-11/12 lg:w-[400px] px-4 py-4 bg-white rounded-md",status:"403",title:"401 未授权"},{footer:X(()=>[G(E(Qe),{class:"w-11/12",value:k.value,"onUpdate:value":oe[1]||(oe[1]=Q=>k.value=Q),type:"password",placeholder:"请输入授权码",maxlength:"60",clearable:""},null,8,["value"]),G(E(ce),{class:"mt-4",secondary:"",type:"info",loading:b.value,onClick:Ce},{default:X(()=>[se("授权")]),_:1},8,["loading"])]),_:1})])):Je("",!0)])

**Comment by SunsetMkt** [comment]
两个方案：
1. 修改`frontend`源码之后重新构建前端，放在`web`里。
2. 直接修改`web`里的文本。

二选一

**Comment by zhangbinhui** [comment]
感谢，在chatgpt的帮助下莫名其妙地实现了，用的是第一种方法
