### ISSUE TITLE
画图后看不到内容

### ISSUE THREAD

**Issue by DavidDengHui** [adams549659584/go-proxy-bingai#34]
如图，创造力模式中画图，有提示画出来了，但是没有显示。
![2023-05-20-20230520030315](https://img.source.host.covear.top/2023-05-20-20230520030315.png "2023-05-20-20230520030315")

**Comment by adams549659584** [comment]
有时候是会这样，对话有时候不画出来，有登录了的话，试试直接访问以下链接看看，后续可能会加个直接画画的窗口。

你的域名/images/create?partner=sydney&re=1&showselective=1&sude=1&kseed=7000&SFX=&q=小狗

**Comment by DavidDengHui** [comment]
可行！居然还能直接使用bing下的images、videos、maps等所有服务！太棒了！
