### ISSUE TITLE
bing加了Turnstile人机检测，所以用不了

### ISSUE THREAD

**Issue by zhuxining** [adams549659584/go-proxy-bingai#348]
Turnstile is a Cloudflare security product designed to stop non-human web visitors.
It works without showing visitors a CAPTCHA.

Sorry, looks like your network settings are preventing access to this feature

**Comment by Xqh-Cxy** [comment]
我这里没问题

**Comment by zhuxining** [comment]
> 我这里没问题

没有登录设置用户cookie，会被拦截；设置“_U”后可以访问

**Comment by directentis1** [comment]
They tweaked something again last night and now I've lost access to it, even though I adjusted the request headers with the modheader.

**Comment by zhuxining** [comment]
> They tweaked something again last night and now I've lost access to it, even though I adjusted the request headers with the modheader.

@directentis1 they add “domain check”, so ...

**Comment by directentis1** [comment]
@zhuxining So, is there any way to bypass it?

**Comment by directentis1** [comment]
![](https://i.imgur.com/x7wv3wW.png)

M$ is damned, they use enough tricks to "force" others to use their products.
 Still can't use Bing in other browsers without fixing UserAgent.
