### ISSUE TITLE
画图功能好像没生效

### ISSUE THREAD

**Issue by AlwaysZmx** [adams549659584/go-proxy-bingai#35]
![image](https://github.com/adams549659584/go-proxy-bingai/assets/29172927/bc694eda-0bc5-49ca-b8b4-b19dafe516fa)
不管是通过web端设置用户cookie还是通过vercel环境变量设置cookie，画图好像始终没有生效

**Comment by AlwaysZmx** [comment]
我基于https://github.com/jianjianai/NewBingGoGo-Web这个项目部署后使用同一个cookie可以画图，但是这个项目为什么画图就不行呢

**Comment by adams549659584** [comment]
有时候对话是没有画，你们试试实际访问画画链接看看行不行，后续看看加个直接画画的窗口

你的域名/images/create?partner=sydney&re=1&showselective=1&sude=1&kseed=7000&SFX=&q=小狗
