### ISSUE TITLE
这个好像是SSL错误，但是Docker哪里能调配置

### ISSUE THREAD

**Issue by 0013227** [adams549659584/go-proxy-bingai#36]
<img width="1440" alt="截屏2023-05-20 07 20 17" src="https://github.com/adams549659584/go-proxy-bingai/assets/93069353/9b8b362a-17fd-4d52-a00c-dd17426c3b37">
3个点一直循环加载
SSL一直报错，内网服务器没法玩SSL，有什么设置关掉它或者调好吗

**Comment by 0013227** [comment]
<img width="1440" alt="截屏2023-05-20 07 20 17" src="https://github.com/adams549659584/go-proxy-bingai/assets/93069353/5303a158-0983-48f6-baec-e26f7e7e3dc4">

**Comment by adams549659584** [comment]
暂时需要 https 的，除了 localhost 不用，浏览器加载微软的脚本的时候的限制，只有在HTTPS的情况下，浏览器 Accept-Encoding 才会包含 br ，之前试过把 微软响应的 br 压缩的内容 改 gzip，但是页面脚本里面还是有 https的限制，就先不搞了。你可以直接部署本地，使用 localhost 访问试试

**Comment by chminsc** [comment]
我也遇到同样的问题。部署在nas上也不能访问。如果部署在远程服务器上，可否加个访问密码？

**Comment by adams549659584** [comment]
后续应该会加个简单的访问密码

**Comment by 0013227** [comment]
<img width="1440" alt="截屏2023-05-20 18 47 24" src="https://github.com/adams549659584/go-proxy-bingai/assets/93069353/3a245da7-4715-41b2-bef2-2da417e957ae">
这还是报错

**Comment by adams549659584** [comment]
> <img alt="截屏2023-05-20 18 47 24" width="1440" src="https://user-images.githubusercontent.com/93069353/239682992-3a245da7-4715-41b2-bef2-2da417e957ae.png"> 这还是报错

这个看不出什么原因，all.js 应该也不是项目里面的，似乎没这个js的，rp 开头的那个得看看有没有加载完成之类的。
