### ISSUE TITLE
手机提问正常，但是电脑端提问报错：Sorry, looks like your network settings are preventing access to this feature.

### ISSUE THREAD

**Issue by yifangyujason** [adams549659584/go-proxy-bingai#362]
手机打开提问正常，但是电脑端提问报错：Sorry, looks like your network settings are preventing access to this feature.

**Comment by yifangyujason** [comment]
![image](https://github.com/adams549659584/go-proxy-bingai/assets/31659735/9318684d-6dcd-417e-8f85-942a33bf7f6c)
用浏览器模拟手机访问，也能正常，求路过的大佬帮忙看看怎么回事

**Comment by gqylmj-guan** [comment]
@yifangyujason 
在设置里，有个设置用户，在里面随便填一些内容。
![image](https://github.com/adams549659584/go-proxy-bingai/assets/52812761/92786e37-c708-47c8-a613-fbfee2e4e127)

**Comment by yifangyujason** [comment]
> @yifangyujason 在设置里，有个设置用户，在里面随便填一些内容。 ![image](https://user-images.githubusercontent.com/52812761/254536870-92786e37-c708-47c8-a613-fbfee2e4e127.png)

感谢解答，不过我早就设置过了，还是一样报错，不过我现在有了解决方案：在nginx里改变User-Agent的值为手机信息
