### ISSUE TITLE
不科学

### ISSUE THREAD

**Issue by SokWith** [adams549659584/go-proxy-bingai#371]
散了散了，连科学上网都有国界了。

![不科学](https://github.com/adams549659584/go-proxy-bingai/assets/129967025/267117e1-83bf-42f0-b655-1ae851be6b07)

账号再次触发验证都没有地方去了。

**Comment by Harry-zklcdc** [comment]
你的问题，我这边使用正常

**Comment by Marsedward** [comment]
> 

现在是只能科学上网了吗？没有办法部署这个了吗？各自尝试都失败啊。大佬有推荐的其他项目吗

**Comment by SokWith** [comment]
> 你的问题，我这边使用正常

测试privado的免费站点，已经封了一大半了，还有2、3个站点没有封。
没封的站点挂上后也一直验证我的微软账号，半天都没有解封。只得重新注册小号才可用。
