### ISSUE TITLE
如何才能绕开微软的域验证，无需上官网进行验证就可以直接使用go-proxy-bingai？

### ISSUE THREAD

**Issue by SmallFang2009** [adams549659584/go-proxy-bingai#372]
![1](https://img1.imgtp.com/2023/07/23/UHqOEkrD.png)
![2](https://img1.imgtp.com/2023/07/23/Uleg5Rak.png)

**Comment by FangZirui-E5** [comment]
用_U值登录并通过官网的域认证才能正常对话

**Comment by chenzhiguo** [comment]
同样的问题，貌似用不了了

**Comment by FangZirui-E5** [comment]
> 同样的问题，貌似用不了了

**Comment by Harry-zklcdc** [comment]
没有办法，没有办法，域名不一样，没法通过人机验证，可查看Cloudflare的人机验证规则

https://github.com/Harry-zklcdc/go-proxy-bingai/issues/23#issuecomment-1647157363

**Comment by nence1** [comment]
现在科学也上官网也提问不了，谁有好办法

**Comment by SmallFang2009** [comment]
科学上网还是可以用的吧，你去看看你的浏览器里有没有记录cn.bing.com的Cookie，有的话删掉试试

**Comment by SmallFang2009** [comment]
> 没有办法，没有办法，域名不一样，没法通过人机验证，可查看Cloudflare的人机验证规则
> 
> [Harry-zklcdc#23 (comment)](https://github.com/Harry-zklcdc/go-proxy-bingai/issues/23#issuecomment-1647157363)

好吧，谢谢

**Comment by chenzhiguo** [comment]
意味着这个项目不能继续愉快的使用了吗？

**Comment by Harry-zklcdc** [comment]
> 意味着这个项目不能继续愉快的使用了吗？

也在想办法解决，但是目前没有进展，CF的人机验证基本上没有绕过的可能，就算有绕过的方法也不会开源，因为一开源两天后就失效了

**Comment by weaigc** [comment]
可以试试这个项目 https://github.com/weaigc/bingo

**Comment by Harry-zklcdc** [comment]
> 可以试试这个项目 https://github.com/weaigc/bingo

这个项目很不错！😊
你的底层似乎是用了ChatHub这个项目的部分代码，是吗？

**Comment by Harry-zklcdc** [comment]
暂时修复了，参考https://github.com/adams549659584/go-proxy-bingai/issues/378

**Comment by SmallFang2009** [comment]
> 暂时修复了，参考#378

太厉害了👍😀（只可惜我没有VPS，用的是vercel，因此没法用docker在云端部署😥）

**Comment by SmallFang2009** [comment]
> 暂时修复了，参考#378

要是有精力的话还是把Vercel的环境变量也研究一下吧🤗谢谢了😀

**Comment by Nothingness-Void** [comment]
分享能用的接入点（无需验证，不用登录）设置用户随便输入点东西就能用
https://github.com/adams549659584/go-proxy-bingai/issues/361#issuecomment-1653628006

**Comment by SokWith** [comment]
> 分享能用的接入点（无需验证，不用登录）设置用户随便输入点东西就能用 [#361 (comment)](https://github.com/adams549659584/go-proxy-bingai/issues/361#issuecomment-1653628006)

低调一点，用得人多了就会如小鸡仔一样，赶紧删除推广吧

**Comment by Nothingness-Void** [comment]
> 分享能用的接入点（无需验证，不用登录）设置用户随便输入点东西就能用 [#361 (comment)](https://github.com/adams549659584/go-proxy-bingai/issues/361#issuecomment-1653628006)

回复一下刚才的哥们，我没找到那条消息但是邮箱里有
服务是搭在微软azure上的，理论来说bing官方服务也是azure上，所以azure的IP应该是最安全的（大概），就是搞一个公益项目希望大家都能用上

**Comment by SokWith** [comment]
> > 分享能用的接入点（无需验证，不用登录）设置用户随便输入点东西就能用 [#361 (comment)](https://github.com/adams549659584/go-proxy-bingai/issues/361#issuecomment-1653628006)
> 
> 回复一下刚才的哥们，我没找到那条消息但是邮箱里有 服务是搭在微软azure上的，理论来说bing官方服务也是azure上，所以azure的IP应该是最安全的（大概），就是搞一个公益项目希望大家都能用上

小鸡仔，双面墙
![image](https://github.com/adams549659584/go-proxy-bingai/assets/129967025/43186f7d-3d05-49f5-9e70-3a3e35aee7a0)

**Comment by Nothingness-Void** [comment]
谢谢大哥好心提醒，我先放一段时间试试，如果不行了我还有两个azure的服务器可以私人用，这个就拿出来做做好事了NothingnessVoid发件人: ***@***.*** ***@***.***> 代表 SokWith ***@***.***>发送时间: 星期四, 七月 27, 2023 10:39:25 下午收件人: go-proxy-bingai ***@***.***>抄送: 1744914510 ***@***.***>; comment ***@***.***>主题: Re: [adams549659584/go-proxy-bingai] 如何才能绕开微软的域验证，无需上官网进行验证就可以直接使用go-proxy-bingai？ (Issue #372)


分享能用的接入点（无需验证，不用登录）设置用户随便输入点东西就能用 #361 (comment)

回复一下刚才的哥们，我没找到那条消息但是邮箱里有 服务是搭在微软azure上的，理论来说bing官方服务也是azure上，所以azure的IP应该是最安全的（大概），就是搞一个公益项目希望大家都能用上

小鸡仔，双面墙

**Comment by SokWith** [comment]
> 可以试试这个项目 https://github.com/weaigc/bingo

可以部署在cf上吗？
https://github.com/weaigc/bingo/issues/13#issue-1827299706

**Comment by Nothingness-Void** [comment]
> > 可以试试这个项目 https://github.com/weaigc/bingo
> 
> 可以部署在cf上吗？ [weaigc/bingo#13 (comment)](https://github.com/weaigc/bingo/issues/13#issue-1827299706)

微软不是封cf的ip了吗 还部署在cf上能行？

**Comment by SokWith** [comment]
> > > 可以试试这个项目 https://github.com/weaigc/bingo
> > 
> > 
> > 可以部署在cf上吗？ [weaigc/bingo#13 (comment)](https://github.com/weaigc/bingo/issues/13#issue-1827299706)
> 
> 微软不是封cf的ip了吗 还部署在cf上能行？

前端时间不行，最近又可以了，包括cf，vercel，replit上免费部署的都可以。

**Comment by Nothingness-Void** [comment]
> > > > 可以试试这个项目 https://github.com/weaigc/bingo
> > > 
> > > 
> > > 可以部署在cf上吗？ [weaigc/bingo#13 (comment)](https://github.com/weaigc/bingo/issues/13#issue-1827299706)
> > 
> > 
> > 微软不是封cf的ip了吗 还部署在cf上能行？
> 
> 前端时间不行，最近又可以了，包括cf，vercel，replit上免费部署的都可以。

哪按理来说这个项目部署在vercel上用worker的应该也能用了

**Comment by SokWith** [comment]
> > > > > 可以试试这个项目 https://github.com/weaigc/bingo
> > > > 
> > > > 
> > > > 可以部署在cf上吗？ [weaigc/bingo#13 (comment)](https://github.com/weaigc/bingo/issues/13#issue-1827299706)
> > > 
> > > 
> > > 微软不是封cf的ip了吗 还部署在cf上能行？
> > 
> > 
> > 前端时间不行，最近又可以了，包括cf，vercel，replit上免费部署的都可以。
> 
> 哪按理来说这个项目部署在vercel上用worker的应该也能用了

是的

> > > > > 可以试试这个项目 https://github.com/weaigc/bingo
> > > > 
> > > > 
> > > > 可以部署在cf上吗？ [weaigc/bingo#13 (comment)](https://github.com/weaigc/bingo/issues/13#issue-1827299706)
> > > 
> > > 
> > > 微软不是封cf的ip了吗 还部署在cf上能行？
> > 
> > 
> > 前端时间不行，最近又可以了，包括cf，vercel，replit上免费部署的都可以。
> 
> 哪按理来说这个项目部署在vercel上用worker的应该也能用了

是的。我就是这样部署的。且把这个部署也可以做NBGoGo的魔法链接使用。

**Comment by Nothingness-Void** [comment]
> > > > > > 可以试试这个项目 https://github.com/weaigc/bingo
> > > > > 
> > > > > 
> > > > > 可以部署在cf上吗？ [weaigc/bingo#13 (comment)](https://github.com/weaigc/bingo/issues/13#issue-1827299706)
> > > > 
> > > > 
> > > > 微软不是封cf的ip了吗 还部署在cf上能行？
> > > 
> > > 
> > > 前端时间不行，最近又可以了，包括cf，vercel，replit上免费部署的都可以。
> > 
> > 
> > 哪按理来说这个项目部署在vercel上用worker的应该也能用了
> 
> 是的
> 
> > > > > > 可以试试这个项目 https://github.com/weaigc/bingo
> > > > > 
> > > > > 
> > > > > 可以部署在cf上吗？ [weaigc/bingo#13 (comment)](https://github.com/weaigc/bingo/issues/13#issue-1827299706)
> > > > 
> > > > 
> > > > 微软不是封cf的ip了吗 还部署在cf上能行？
> > > 
> > > 
> > > 前端时间不行，最近又可以了，包括cf，vercel，replit上免费部署的都可以。
> > 
> > 
> > 哪按理来说这个项目部署在vercel上用worker的应该也能用了
> 
> 是的。我就是这样部署的。且把这个部署也可以做NBGoGo的魔法链接使用。

我试了一下，vercel上的还是不行，只有我两个搭在az上的能用

**Comment by weaigc** [comment]
> > > > 可以试试这个项目 https://github.com/weaigc/bingo
> > > 
> > > 
> > > 可以部署在cf上吗？ [weaigc/bingo#13 (comment)](https://github.com/weaigc/bingo/issues/13#issue-1827299706)
> > 
> > 
> > 微软不是封cf的ip了吗 还部署在cf上能行？
> 
> 前端时间不行，最近又可以了，包括cf，vercel，replit上免费部署的都可以。

@chenzhiguo 还有是封的，只不过没之前那么严格，目前就hf是完全没有被封杀的
