### ISSUE TITLE
 在Windows中如何启动它 在Windows中如何启动它  How to start it in Windows

### ISSUE THREAD

**Issue by 2662007798** [adams549659584/go-proxy-bingai#38]
我该如何启动它？
How should I start it？

**Comment by adams549659584** [comment]
下载对应windows平台的release，直接双击就可以运行。部署的服务器需要可以直连 www.bing.com 的

**Comment by XieWenbo123** [comment]
没用会显示：很抱歉，似乎出现错误。 让我们重新开始吧。

**Comment by 2662007798** [comment]
> 

有这个链接吗？ 我找不到release的下载地址。。。。

**Comment by adams549659584** [comment]
> > 
> 
> 有这个链接吗？ 我找不到release的下载地址。。。。

https://github.com/adams549659584/go-proxy-bingai/releases
