### ISSUE TITLE
我该如何编译它？

### ISSUE THREAD

**Issue by 2662007798** [adams549659584/go-proxy-bingai#39]
怎么编译和启动啊？？？？我想用nginx

**Comment by adams549659584** [comment]
编译可以参考 Taskfile 中的命令，几乎所有平台的编译都在里面了，Release 有编译好的 windows 和 linux 的

**Comment by 2662007798** [comment]
> 编译可以参考 Taskfile 中的命令，几乎所有平台的编译都在里面了，Release 有编译好的 windows 和 linux 的

我该怎么改它的端口直接运行release的话

**Comment by adams549659584** [comment]
> > 编译可以参考 Taskfile 中的命令，几乎所有平台的编译都在里面了，Release 有编译好的 windows 和 linux 的
> 
> 我该怎么改它的端口直接运行release的话

设置环境变量 PORT 就行，所有的环境变量在 项目首页有说明的
