### ISSUE TITLE
怎么更新呢？

### ISSUE THREAD

**Issue by HaiVong** [adams549659584/go-proxy-bingai#4]
大佬。使用宝塔里的docker compose搭建的，如何更新新版本呢？
还有能否直接使用宝塔的常规网站搭建方式进行搭建呢？

**Comment by adams549659584** [comment]
```bash
# 拉取最新并更新就好
docker-compose pull && docker-compose up -d
```

**Comment by adams549659584** [comment]
宝塔没怎么用过，常规网站是支持php之类的话，应该不行。

**Comment by HaiVong** [comment]
> 

感谢，docker刚开始用，还在一点点摸索，用现成的管理面板用习惯了，突然用这个还有点不习惯

**Comment by HaiVong** [comment]
使用同一个ck，在大佬你的演示网站上就能正常出图，但是在我自己的搭建的上面就不出图
只显示下面图片上的这个，
我是用的日本IP的服务器，和这个不知道有没有关系。不知道这里能不能发网址
![QQ截图20230506154258](https://user-images.githubusercontent.com/91323283/236610972-5baff78d-ec03-4d15-8ff4-c7b29f7616b2.jpg)

**Comment by adams549659584** [comment]
我的甲骨文的也是日本的，应该没关系。已经更新最新版本了的话，在浏览器 F12 或 Ctrl + Shift + I ，看看有没有报什么错误。之前版本的随机IP有点问题，会有中国IP，早上改为美国真实IP段了。
