### ISSUE TITLE
错误层出不穷，来完SSL又来这个鬼

### ISSUE THREAD

**Issue by 0013227** [adams549659584/go-proxy-bingai#41]
<img width="1436" alt="截屏2023-05-20 21 06 21" src="https://github.com/adams549659584/go-proxy-bingai/assets/93069353/da6ad440-2005-421a-b0a1-fb32d5f5b2f0">

**Comment by adams549659584** [comment]
这个没看出什么原因，all.js 应该不是项目中的，其他的像全部请求失败了

**Comment by 0013227** [comment]
后面改了一下，发现只剩代理错误了，真是搞懵了，代理用第二行的Docker命令还无效，还要手动再配置一个代理端吗？有没有教程

**Comment by adams549659584** [comment]
国内机器？那个 SOCKS 是你可以直连 www.bing.com 的代理来的，没有的话，可以尝试其他几种免费部署的方式
