### ISSUE TITLE
close issue

### ISSUE THREAD

**Issue by ghostWindows-files** [adams549659584/go-proxy-bingai#415]
这个私人盗版[Harry-zklcdc](https://github.com/Harry-zklcdc/go-bingai-pass/commits?author=Harry-zklcdc)
Harry-zklcdc的仓库

**Comment by Harry-zklcdc** [comment]
我代码除了人机验证都开源了，作者也说不维护了，还有什么正版盗版，**更何况我已经在显眼位置留下了原作者的开源信息**，根本没有违反 MIT 开源协议😅

发表言论前请依据开源社区规则，谢谢

**Comment by Harry-zklcdc** [comment]
而且你链接中的仓库是部署人机验证用的，是我后来更新的功能，原仓库的 fork 关系我依旧保留，没有去除

<img width="505" alt="image" src="https://github.com/adams549659584/go-proxy-bingai/assets/21104213/90b699c1-9c35-4065-989f-4f0574b743b2">

**Comment by Cccc-owo** [comment]
符合开源协议，何来盗版之说？

**Comment by ryanzhaorx** [comment]
Harry-zklcdc是符合MIT的开源协议，已经在留下原作者的开源信息，并且[go-bingai-pass](https://github.com/Harry-zklcdc/go-bingai-pass)是他自己的项目(人机验证服务器)，与本项目(go-proxy-bingai)无关。请close本issue。
