### ISSUE TITLE
局域网内启动其他电脑访问有问题

### ISSUE THREAD

**Issue by 1472709337** [adams549659584/go-proxy-bingai#43]
在局域网内的一台arm版系统的windows11上启动了软件
其他电脑访问会一直处于加载中(如图)
本身浏览却没有问题
![image](https://github.com/adams549659584/go-proxy-bingai/assets/101865709/7c9cfa41-9a72-41ef-a479-189fef98f8dc)

**Comment by 0013227** [comment]
肯定是SSL出了异常，用IP访问弄不了HTTPS，但是localhost就没事，F12打开你的浏览器控制台看看有无报错

**Comment by 0013227** [comment]
你在arm版系统的windows11上启动的BingAI能正常问问题吗

**Comment by adams549659584** [comment]
暂时只能 https 访问的，localhost 除外
