### ISSUE TITLE
直接访问 域名/create 会暴露邮箱及微软账号详情

### ISSUE THREAD

**Issue by zixiwangluo** [adams549659584/go-proxy-bingai#44]
如果内置了ck的情况下，会暴露网站主的微软邮箱地址，即使那是不重要的邮箱，但依然存在部分隐私泄露问题，请尝试处理该问题，我不知道它是否为bug？

**Comment by adams549659584** [comment]
所以不推荐使用内置的，之前很多人说要才加的，多人共用账号很快就会触发验证，也很快会达到24小时限制的，都是针对账号的。后续有空应该会加个简单授权，对于个人使用应该没啥问题的。
