### ISSUE TITLE
设置菜单和谷歌统计问题

### ISSUE THREAD

**Issue by xfxx2022** [adams549659584/go-proxy-bingai#45]
你好
 请问右上角设置菜单怎样修改或者自定义，谷歌统计在哪里删除或者修改

**Comment by lwd-temp** [comment]
谷歌统计只能在 https://github.com/adams549659584/go-proxy-bingai/blob/master/web/index.html#L19 和 https://github.com/adams549659584/go-proxy-bingai/blob/master/web/compose.html#L18 手动删除。

这个前端项目实际上在 https://github.com/adams549659584/go-proxy-bingai/tree/master/frontend ，应该可以自己修改并重新构建。

**Comment by adams549659584** [comment]
是的，前端源码在 frontend 中，修改后先编译前端代码，再编译 go 就可以，具体所有命令都可以在 Taskfile 中看。

**Comment by xfxx2022** [comment]
> 是的，前端源码在 frontend 中，修改后先编译前端代码，再编译 go 就可以，具体所有命令都可以在 Taskfile 中看。

咱是小白，有没有简单的方法...直接修改文件内容什么的
