### ISSUE TITLE
docker 部署后访问页面只展示加载等待的三个点，无法正常载入页面。

### ISSUE THREAD

**Issue by wpvec** [adams549659584/go-proxy-bingai#46]
Docker 部署的，Nginx已经使用域名做了转发，但是页面只有三个点加载，无法展示主页。
![image](https://github.com/adams549659584/go-proxy-bingai/assets/26601366/17e64d77-9151-4310-956e-948f6498a3b7)
这个问题是哪里的原因，请求指点。

**Comment by adams549659584** [comment]
可能是https证书问题吧，浏览器显示不安全

**Comment by qhdypkt** [comment]
不是https证书问题，我也遇到了相同的问题。解决方法是，点击右上角的设置，选择一键重置，就正常了，你可以试一试。

**Comment by wpvec** [comment]
> 

我的cookies等信息都清理了好多次了，并不可行~ 我再重新试试解决证书的问题。

**Comment by wpvec** [comment]
> 不是https证书问题，我也遇到了相同的问题。解决方法是，点击右上角的设置，选择一键重置，就正常了，你可以试一试。

我的cookies等信息都清理了好多次了，并不可行~ 我再重新试试解决证书的问题。

**Comment by Zayia** [comment]
换一个机器或者浏览器试试

**Comment by wpvec** [comment]
> 可能是https证书问题吧，浏览器显示不安全

证书的问题解决了，但是现象看起来还是没有变化，还可能有其他原因吗？
![image](https://github.com/adams549659584/go-proxy-bingai/assets/26601366/c798c27a-9db7-4edf-8054-4051bbbc3d80)
我已经做了以下尝试：
1. 测试打开您的 [bing.vcanbb.top](https://bing.vcanbb.top/) 页面是没问题的。
2. cookies清理 -- 没有效果
3. 一键重置 -- 没有效果
4. 更换浏览器 -- 没有效果
    Microsoft Edge 版本 115.0.1851.0 (正式版本) dev (64 位)
    Google Chrome版本 105.0.5195.127（正式版本） （64 位）

**Comment by adams549659584** [comment]
![image](https://github.com/adams549659584/go-proxy-bingai/assets/10492939/ce7a1ff2-28f4-4e64-9309-45b387967ae0)
这些 /rp/ 开头的脚本是聊天的核心代码来的，等加载完毕，看看这些有没有报错

**Comment by wpvec** [comment]
> ![image](https://user-images.githubusercontent.com/10492939/239817662-ce7a1ff2-28f4-4e64-9309-45b387967ae0.png) 这些 /rp/ 开头的脚本是聊天的核心代码来的，等加载完毕，看看这些有没有报错

br的两个请求全都 504 了，难道是代理网络的问题吗？
我这边也测试了下，代理在 docker 内部是生效的。
![image](https://github.com/adams549659584/go-proxy-bingai/assets/26601366/045c2bf3-9a15-446a-93c4-48e7f914da9d)
您这边还有什么其他建议吗？ 我这边自己也查查看~

**Comment by adams549659584** [comment]
> > ![image](https://user-images.githubusercontent.com/10492939/239817662-ce7a1ff2-28f4-4e64-9309-45b387967ae0.png) 这些 /rp/ 开头的脚本是聊天的核心代码来的，等加载完毕，看看这些有没有报错
> 
> br的两个请求全都 504 了，难道是代理网络的问题吗？ ![image](https://user-images.githubusercontent.com/26601366/239826919-32b45b8b-dbb2-4f3d-bea1-d783bd7d255d.png)
> 
> 我这边也测试了下，代理在 docker 内部是生效的。 ![image](https://user-images.githubusercontent.com/26601366/239826418-045c2bf3-9a15-446a-93c4-48e7f914da9d.png) 您这边还有什么其他建议吗？ 我这边自己也查查看~

你在里面 ping 下 www.bing.com 看看，服务器要能直连  www.bing.com 的

**Comment by wpvec** [comment]
ping 的结果是这个：
![image](https://github.com/adams549659584/go-proxy-bingai/assets/26601366/ab3ccea7-35c7-441e-a862-f9092348731d)

**Comment by adams549659584** [comment]
你可以试试在服务器上直接访问这个脚本看看是不是正常响应的，再慢慢一步步排查其他的吧
```bash
 curl -I http://127.0.0.1:8080/rp/oJ7sDoXkkNOICsnFb57ZJHBrHcw.br.js
```

**Comment by wpvec** [comment]
> 你可以试试在服务器上直接访问这个脚本看看是不是正常响应的，再慢慢一步步排查其他的吧
> 
> ```shell
>  curl -I http://127.0.0.1:8080/rp/oJ7sDoXkkNOICsnFb57ZJHBrHcw.br.js
> ```

是不是坐实代理的问题了？ 我晚上再换个试试看，谢谢了~
![image](https://github.com/adams549659584/go-proxy-bingai/assets/26601366/2b096a8e-0872-4fa2-a1bc-4a1a3c391eff)

**Comment by adams549659584** [comment]
本地都不能访问的话，应该是有问题的，正常的话，是响应下面这样的
![1684746686232](https://github.com/adams549659584/go-proxy-bingai/assets/10492939/d2fdee50-d352-4fd3-9f24-8f40b0a3c55c)

**Comment by JohyC** [comment]
欸！大佬！本地访问是正常；
nginx 反代访问就不行呀... 感觉像是说我代理不行。不太懂了
![image](https://github.com/adams549659584/go-proxy-bingai/assets/38210128/754828c6-b499-4e9d-a226-17b8360e90a4)
![image](https://github.com/adams549659584/go-proxy-bingai/assets/38210128/e74faee6-c52d-4e3f-add0-d9aa26e5d2ab)
