### ISSUE TITLE
关于不开代理无法使用的问题

### ISSUE THREAD

**Issue by fyypll** [adams549659584/go-proxy-bingai#48]
我这边搭建在了甲骨文的服务器上，不知道为什么无法使用，首先是手机端，打开无限三个点，一直加载，但是右上角的齿轮倒是加载出来了，使用了齿轮中的重置功能也还是一直加载。pc端是可以正常加载页面的。

还有就是我这边使用的话，本地不开代理是无法使用的，在web界面会显示   **正在尝试重新连接...**  字样。控制台显示 链接 **wss://sydney.bing.com/sydney/ChatHub** 失败。在写作页面，控制台显示 **链接 www2.bing.com 失败**。

当然，我不开代理访问项目演示站点 bing.vcanbb.top 也是会有同样的问题，所以应该不是我的部署问题

不是走的服务器的代理吗？为什么会是本地直接连 *.bing.com ？

我不知道大家是否使用都是正常的，但是我这里确实遇到这个问题。当然我也不知道是不是我这边的网络问题，反正目前还没有找到原因

**Comment by adams549659584** [comment]
对话（wss://sydney.bing.com/sydney/ChatHub）是直连的 bing 的，这个在国内可用的。
手机端暂时发现夸克无法加载脚本，可以试试其他浏览器。
我的也是甲骨文的，暂时是可用的，你可以尝试下完全关掉代理，刷新dns试试，只是代理开关之类的可能有问题。

**Comment by Duorhs** [comment]
我也有同样的问题，同一个网络环境下，有时可以使用，有时候会出现websocket建立失败。如果我开启代理，就会提示无效域，控制台输出为[Cloudflare Turnstile] invalid_domain.

**Comment by cubhua** [comment]
有解决这个问题的大佬吗？愿意付费

**Comment by Jiashisoft** [comment]
sydney.bing有的网被墙的，所以就这样了

**Comment by adams549659584** [comment]
参考 #67
