### ISSUE TITLE
使用docke run 搭建，出现很抱歉，似乎出现错误。

### ISSUE THREAD

**Issue by sadtear** [adams549659584/go-proxy-bingai#5]
![网页捕获_6-5-2023_174036_qvqai xyz](https://user-images.githubusercontent.com/53419610/236616404-eec00ece-8f4c-4bd5-a077-65cb6d8a9ea9.jpeg)

已经使用https，已更新。开无痕也试过了。服务器是华盛顿的

**Comment by adams549659584** [comment]
浏览器中 F12 或 Ctrl + Shift + I 打开开发者工具，看看控制台有没有什么错误，还可以点下仿真模式，模拟手机试试，看手机是不是秒创建会话。刚发现未登录用户，微软应该优先手机了，最新版本代码已经发布。

**Comment by sadtear** [comment]
感谢！使用模拟手机后就可以使用了。回到电脑模式后，也正常了。

1，控制台中一直报 ‘’net::ERR_NAME_NOT_RESOLVED 这个错误，但是感觉没什么影响。
2，关于Nginx的配置，是否在国外的服务器就不需要配置了呢？

**Comment by adams549659584** [comment]
1. 那应该就是刚刚说的那个问题了，最新版已经修复，可以更新下，你这里只是暂时用手机模式获取到会话了。
2. 你可以尝试下，忘了 http 有啥问题来着，nginx 不是必须的，只要能 https 访问都可以。

**Comment by adams549659584** [comment]
好用的话，记得 star 下😁

**Comment by sadtear** [comment]
必须的！ 已 star ~

1，我已经使用docker重新部署更新了，只是我使用的宝塔上的docker来部署的，（按理这个应该不会影响，），因为我是把之前的全部删除后，重新使用命令来部署。

2，目前来看，现在又不能使用了，使用了手机访问也不行。

3，或许大佬可以加个版本好之类的标识？因为现在有点不确定到底有没有更新到了最新的版本。

**Comment by adams549659584** [comment]
1. 浏览器控制台中有输出版本号的，例如：Service Worker Version: v1.3.5
2. 未登录用户应该是优先手机端了，所以最新版本代码加了模拟手机了。

**Comment by sadtear** [comment]
感谢您的指导！
1，宝塔面板的问题，好像不可以在原有上更新，之前一直是1.3.4版本，我寻找到了您dockerhub上的库，删除了原有的重新部署后，即是1.3.5版本。
2，体验良好，使用cookie登录后，使用创造力的还是无法生成图片。控制中报错为
【Failed to load resource: net::ERR_NAME_NOT_RESOLVED】，可能是宝塔面板的其它问题，我稍晚使用直接的docker面板试试。

**Comment by adams549659584** [comment]
好的，不用客气😁
