### ISSUE TITLE
匿名使用没事，一旦设置用户里面填写了cookie就开始报错

### ISSUE THREAD

**Issue by Zayia** [adams549659584/go-proxy-bingai#50]
匿名使用没事，一旦设置用户里面填写了cookie就开始报错
提示
 很抱歉，似乎出现错误。 让我们重新开始吧。

**Comment by adams549659584** [comment]
要检查下有没有填错，账号有没有问题，这边暂时还是可以的

**Comment by Zayia** [comment]
> 要检查下有没有填错，账号有没有问题，这边暂时还是可以的

账号正常，cookie也按照教程来的，没错

**Comment by adams549659584** [comment]
> > 要检查下有没有填错，账号有没有问题，这边暂时还是可以的
> 
> 账号正常，cookie也按照教程来的，没错

你可以试试填写 cookie 后，在浏览器打开控制台看看，刷新，提问，看看接口 /turing/conversation/create 的响应内容。

**Comment by Zayia** [comment]
![image](https://github.com/adams549659584/go-proxy-bingai/assets/35530837/1400981c-25ab-490f-addd-173272aa52d0)
控制台是这样的
相应内容如下：
`{"conversationId":"51D|BingProdUnAuthenticatedUsers|CE0BFC6EBCA95A8FB139231B7E9B31E9F87962D0909B7728C3CFFA550F67B608","clientId":"844428454568331","conversationSignature":"jvyunM8eU\u002B9PCwSzoRa6AtPv/ohBXGMCAN16VjSIVB4=","result":{"value":"Success","message":null}}`

**Comment by adams549659584** [comment]
这个是未授权的，填写cookie后，刷新下，在网络请求里面看看对应的接口 /turing/conversation/create 的响应内容

**Comment by Zayia** [comment]
填写cookie后，网络请求里面没有/turing/conversation/create这个
填写前有

**Comment by adams549659584** [comment]
随便提问下就会有了的

**Comment by Zayia** [comment]
问了也没有
`https://nb.57263382.xyz:16666/web/#/`
上面是地址，大佬你可以试一下
我生产环境是docker+反向代理

**Comment by adams549659584** [comment]
参考下这个配置，加下这几个请求头试试，看了下脚本中获取到的http来的
https://github.com/adams549659584/go-proxy-bingai/issues/27#issuecomment-1554167457

**Comment by Harry-zklcdc** [comment]
已修复，https://github.com/adams549659584/go-proxy-bingai/issues/282
