### ISSUE TITLE
大佬，我直接在go-proxy-bingai/docker 下执行 docker build -t bing-chat . 报错了

### ISSUE THREAD

**Issue by zhangbinhui** [adams549659584/go-proxy-bingai#51]
=> ERROR [builder 4/4] RUN go build -ldflags="-s -w" -tags netgo -trimpath -o go-proxy-bingai main.go                                                                                                                           0.4s
------
 > [builder 4/4] RUN go build -ldflags="-s -w" -tags netgo -trimpath -o go-proxy-bingai main.go:
#0 0.391 no required module provides package main.go: go.mod file not found in current directory or any parent directory; see 'go help modules'
------
Dockerfile:4
--------------------
   2 |     WORKDIR /app
   3 |     COPY . .
   4 | >>> RUN go build -ldflags="-s -w" -tags netgo -trimpath -o go-proxy-bingai main.go
   5 |     
   6 |     FROM alpine
--------------------
ERROR: failed to solve: process "/bin/sh -c go build -ldflags=\"-s -w\" -tags netgo -trimpath -o go-proxy-bingai main.go" did not complete successfully: exit code: 1

怎么修复，是我执行的路径不对吗？还是这个Dockerfile有问题？搞不定

**Comment by adams549659584** [comment]
指定 上下文，在外面根目录，或者外面根目录执行，指定docker文件路径

**Comment by zhangbinhui** [comment]
> 指定 上下文，在外面根目录，或者外面根目录执行，指定docker文件路径

可以的，感谢
