### ISSUE TITLE
您好，请问 创建会话ID失败 这个问题该如何解决

### ISSUE THREAD

**Issue by mzsj2214474136** [adams549659584/go-proxy-bingai#52]
![image](https://github.com/adams549659584/go-proxy-bingai/assets/105125393/1a3e6ec2-eb0f-48e5-bc4f-bff55e684f1d)

**Comment by zxy003512** [comment]
![image](https://github.com/adams549659584/go-proxy-bingai/assets/132435711/e17788e6-1223-460e-b6f3-2fd428fdb856)

**Comment by mzsj2214474136** [comment]
当我使用 Railway 搭建时，出现这个问题
![图片](https://github.com/adams549659584/go-proxy-bingai/assets/105125393/c30c5566-5985-4a78-b5d0-1a5ad041c468)

**Comment by adams549659584** [comment]
sysney.bing.com 应该被墙了，个人主站先紧急修复了下，小鸡仔能不能撑住就不知道了。

**Comment by nishaui99** [comment]
> ![image](https://user-images.githubusercontent.com/105125393/240000542-1a3e6ec2-eb0f-48e5-bc4f-bff55e684f1d.png)

我也同样出现这个问题。请问解决了没有，呆呆我

**Comment by adams549659584** [comment]
> > ![image](https://user-images.githubusercontent.com/105125393/240000542-1a3e6ec2-eb0f-48e5-bc4f-bff55e684f1d.png)
> 
> 我也同样出现这个问题。请问解决了没有，呆呆我

你的服务器可以直连 www.bing.com 吗？看起来是要跳去 CN 了，可以直连的话，一件重置下试试

**Comment by kinomotom** [comment]
> > > ![image](https://user-images.githubusercontent.com/105125393/240000542-1a3e6ec2-eb0f-48e5-bc4f-bff55e684f1d.png)
> > 
> > 
> > 我也同样出现这个问题。请问解决了没有，呆呆我
> 
> 你的服务器可以直连 [www.bing.com](http://www.bing.com) 吗？看起来是要跳去 CN 了，可以直连的话，一件重置下试试

不行。curl www.bing.com 没有响应

**Comment by mzsj2214474136** [comment]
该问题，要检查一下你的代理，我没有设置代理的时候，出现了，设置代理后成功运行
