### ISSUE TITLE
现在使用不了，求作者能修复，如果稳定，愿意付费

### ISSUE THREAD

**Issue by xiaoyaoxiong7** [adams549659584/go-proxy-bingai#54]
换了多个cookies还是不能正常访问

作者创作不易，建议坐着拉一个付费小群，稳定更新，一方面使用的人太多封杀太快，另一方面支持一下作者

**Comment by adams549659584** [comment]
sysney.bing.com 应该被墙了，个人主站先紧急修复了下，小鸡仔能不能撑住就不知道了。

**Comment by zhangbinhui** [comment]
> sysney.bing.com 应该被墙了，个人主站先紧急修复了下，小鸡仔能不能撑住就不知道了。

是不是类似 https://github.com/linweiyuan/go-chatgpt-api/blob/main/README_zh.md 这个里面提到的，用cloudflare的warp来解决问题，供大佬参考

**Comment by SpartanH7** [comment]
应该是这个项目只代理了创建会话的部分，后面的消息使用wss传输的没有用服务器代理，只能等作者把这部分的代理加上了，给作者推荐一下这个项目https://github.com/acheong08/EdgeGPT ，用python写的newbing代理，代码很简洁，可以参考一下

**Comment by lwd-temp** [comment]
> sysney.bing.com 应该被墙了，个人主站先紧急修复了下，小鸡仔能不能撑住就不知道了。

应该不是墙，更像是Bing检测中国IP。
https://blocky.greatfire.org/detail/557231/https%3A%2F%2Fsydney.bing.com

**Comment by willggy** [comment]
用这个插件修改下请求头
![image](https://github.com/adams549659584/go-proxy-bingai/assets/74762604/40d74e87-76f1-4679-b4ec-55b28cf24575)
