### ISSUE TITLE
windows下环境变量在哪里设置？

### ISSUE THREAD

**Issue by QwindF** [adams549659584/go-proxy-bingai#56]
在releases下载了1.7版本的[go-proxy-bingai-windows-amd64.tar.gz](https://github.com/adams549659584/go-proxy-bingai/releases/download/v1.7.0/go-proxy-bingai-windows-amd64.tar.gz)
不知道在哪里修改环境变量，也没有看到配置文件。
还有发现打开之后的版本号还是显示1.6.8

**Comment by ryxxjyx** [comment]
右键“此电脑”----“属性”---“高级系统设置”----环境变量

**Comment by adams549659584** [comment]
一键重置下看看，可设置系统环境变量 或 临时环境变量，直接搜索下就有
