### ISSUE TITLE
有没有大佬尝试去搞定这个验证码验证...

### ISSUE THREAD

**Issue by wintrue** [adams549659584/go-proxy-bingai#58]
![image](https://github.com/adams549659584/go-proxy-bingai/assets/6380530/16e8af38-a98b-494e-83c7-badcc8692f25)

**Comment by wintrue** [comment]
![image](https://github.com/adams549659584/go-proxy-bingai/assets/6380530/f59fe97a-a3b7-48db-8169-7cec42004fb7)

哈哈

**Comment by QwindF** [comment]
怎么触发的？用了这么久都没碰到过
