### ISSUE TITLE
WebSocket connection to 'wss://sydney.bing.com/sydney/ChatHub' failed:

### ISSUE THREAD

**Issue by lmuiotctf** [adams549659584/go-proxy-bingai#59]
目前会报wss错误
![image](https://github.com/adams549659584/go-proxy-bingai/assets/52068443/7dfad147-a269-409b-91d0-a6ad02e6e22f)

**Comment by rakaki** [comment]
其他issue里作者说原因了，在修复

**Comment by Jiashisoft** [comment]
+1

**Comment by Jiashisoft** [comment]
作者大佬说的没错，wss连接不上的原因是sydney.bing被墙了。如果你本地机器有科学上网，打开后还是能正常回复使用的

**Comment by lmuiotctf** [comment]
我的vps就是美国的机子呢

**Comment by lwd-temp** [comment]
> 我的vps就是美国的机子呢

和`sydney.bing.com`的连接不走代理（前端实现），目前它禁止了中国IP访问。

**Comment by macvip** [comment]
感觉不是被墙了，而是微软禁止了中国IP访问

> > 我的vps就是美国的机子呢
> 
> 和`sydney.bing.com`的连接不走代理（前端实现），目前它禁止了中国IP访问。

**Comment by jofar** [comment]
> 感觉不是被墙了，而是微软禁止了中国IP访问
> 
> > > 我的vps就是美国的机子呢
> > 
> > 
> > 和`sydney.bing.com`的连接不走代理（前端实现），目前它禁止了中国IP访问。

同感。 1.7.1版的应已改为服务端实现了， 应该改了，只是没有放出来。

**Comment by adams549659584** [comment]
参考 #67
