### ISSUE TITLE
很抱歉，似乎出现了错误

### ISSUE THREAD

**Issue by Young-Chan2020** [adams549659584/go-proxy-bingai#6]
怎么解决

**Comment by adams549659584** [comment]
浏览器中 F12 或 Ctrl + Shift + I 打开开发者工具，看看控制台有没有什么错误，看看当前版本号，控制台会输出，例如：Service Worker Version: v1.3.5，最重要的是 ，部署的服务器，是需要能直连 www.bing.com 的
