### ISSUE TITLE
lz你的甲骨文小鸡仔也挂了

### ISSUE THREAD

**Issue by justincnn** [adams549659584/go-proxy-bingai#60]
https://bing.vcanbb.top/

我们自己搭建的无法使用，你的小鸡仔也挂了 ：（

**Comment by QwindF** [comment]
还可以使用
包括自建和作者建的

**Comment by justincnn** [comment]
> 还可以使用 包括自建和作者建的

是自带梯子的那种么？

**Comment by rakaki** [comment]
看项目右上的，用modheader就可以

**Comment by wendel-ywt** [comment]
自建的得用梯子，否则一直卡在重新连接这个界面

**Comment by jofar** [comment]
正在尝试连接，请稍候， 不能用了， 挂梯子也不行。

**Comment by macvip** [comment]
将这里[config.js](https://github.com/adams549659584/go-proxy-bingai/blob/842e02b9d7ae765942e166779a3bf84ead2b8d12/web/js/bing/chat/config.js#L27)和frontend/public下对应的地方改成`sydBaseUrl: location.origin`
然后再重新部署自己的服务器就可以了，也不用mod header修改请求头。
但是不知道这种方法能坚持多久。大家偷偷用，别奔走相告啊

**Comment by gitMFQ** [comment]
> 将这里[config.js](https://github.com/adams549659584/go-proxy-bingai/blob/842e02b9d7ae765942e166779a3bf84ead2b8d12/web/js/bing/chat/config.js#L27)和frontend/public下对应的地方改成`sydBaseUrl: location.origin`
> 然后再重新部署自己的服务器就可以了，也不用mod header修改请求头。
> 但是不知道这种方法能坚持多久。大家偷偷用，别奔走相告啊

改完后完全用不了了。

**Comment by rakaki** [comment]
> 

我fork了一份，改了重新部署之后还是不行啊

**Comment by adams549659584** [comment]
参考 #67
