### ISSUE TITLE
[建议]是否可以增加一个用户设置

### ISSUE THREAD

**Issue by justincnn** [adams549659584/go-proxy-bingai#61]
因为个人习惯和隐私的需求，基本都是以自用id为主，是否可以增加一个设置用户注册登陆的权限。

或者说，是否可以增加ms官方账号的关联，以最大程度的保护自己的id

希望可以采纳，谢谢

**Comment by adams549659584** [comment]
暂时不加，自行搭建，自行使用，为什么要要注册登录？
