### ISSUE TITLE
Vercel部署后无法获取回答

### ISSUE THREAD

**Issue by Kaol-Fu** [adams549659584/go-proxy-bingai#64]
Vercel 一键部署成功，访问页面正常。但是在使用的时候，无法获取 Newbing 的回答，出现“Invalid domain. Contact the Site Administrator if this problem persists.”的字样。

**Comment by adams549659584** [comment]
> Vercel 一键部署成功，访问页面正常。但是在使用的时候，无法获取 Newbing 的回答，出现“Invalid domain. Contact the Site Administrator if this problem persists.”的字样。

这个应该是触发 cloudflare 验证了，暂时只能去官网验证下先
