### ISSUE TITLE
无法使用，不开梯子一直显示正在重新连接。。还是没办法用啊。。是更新了吗？

### ISSUE THREAD

**Issue by aotian666666** [adams549659584/go-proxy-bingai#67]

**Comment by rakaki** [comment]
看项目主页about，用modheader改请求头

**Comment by shangaokun** [comment]
修改一下X-Forwarded-For就行

**Comment by aotian666666** [comment]
> 修改一下X-Forwarded-For就开始

怎么改？改完是否还能给别人用了？ 其他人用也许改一遍吗？

**Comment by shangaokun** [comment]
> > 修改一下X-Forwarded-For就开始
> 
> 怎么改？改完是否还能给别人用了？ 其他人用也许改一遍吗？

大佬介绍里面写了：
`⭐ 自行搭建的可先用 ModHeader 添加 X-Forwarded-For 请求头，对应 URL 是 wss://sydney.bing.com/sydney/ChatHub ，暂时可用 ，可参考 https://zhuanlan.zhihu.com/p/606655303 ⭐ 主站服务器转发的，相对直连官网，会卡很多，等后续看看有没有更好的方式，再提交版本更新。`
因为这个是每个人的浏览器都要访问wss://sydney.bing.com/sydney/ChatHub，每个人都需要改，我的配置现在这样子：
![image](https://github.com/adams549659584/go-proxy-bingai/assets/15159334/2eecdc96-e6ef-4894-835a-32f0d8a297db)

手机推荐用猴狐浏览器，可以装插件。

**Comment by aotian666666** [comment]
> > > 修改一下X-Forwarded-For就开始
> > 
> > 
> > 怎么改？改完是不是还能给别人用了？其他人用也许改一遍吗？
> 
> 大佬介绍里面写了： `⭐ 自行搭建的可先用 ModHeader 添加 X-Forwarded-For 请求头，对应 URL 是 wss://sydney.bing.com/sydney/ChatHub ，暂时可用 ，可参考 https://zhuanlan.zhihu.com/p/606655303 ⭐ 主站服务器转发的，相对直连官网，会卡很多，等后续看看有没有更好的方式，再提交版本更新。` 因为这个是每个人的浏览器都要访问wss://sydney.bing.com/sydney/ChatHub，每个人都需要改，我的配置现在这样子： ![图像](https://user-images.githubusercontent.com/15159334/240810831-2eecdc96-e6ef-4894-835a-32f0d8a297db.png)
> 
> 手机推荐使用猴狐浏览器，可以安装插件。

谢谢大佬，要是能把这个复杂的环节给优化掉就好啦

**Comment by adams549659584** [comment]
最新版 v1.8.0 新增 clodflare 聊天服务器，相对直连官网，还是会卡的，推荐直连，设置请求头。
