### ISSUE TITLE
能不能直接在代码里改X-Forwarded-For

### ISSUE THREAD

**Issue by gitMFQ** [adams549659584/go-proxy-bingai#68]
能不能直接在直接在代码里改X-Forwarded-For？
不懂别笑话我啊

**Comment by shangaokun** [comment]
代码里面改了也只是经过服务器的X-Forwarded-For请求做修改，你自己的浏览器还是要直接访问wss://sydney.bing.com/sydney/ChatHub，这个websocket链接不经过服务器，只能在浏览器客户端修改。

**Comment by gitMFQ** [comment]
我寻思各种插件不是基本都js嘛，代码里加上相关js是不是就行了

**Comment by shangaokun** [comment]
主要是客户端和服务器端的问题，理论上客户端下载js运行wss://sydney.bing.com/sydney/ChatHub都可以给他代理了，我看这个回答里面有改js的信息。
![image](https://github.com/adams549659584/go-proxy-bingai/assets/15159334/b5af278f-056f-429c-a517-104943918f78)
但我只会玩后台java，前端不熟，只会直接部署docker，坐等大佬解决更新。

**Comment by crazybber** [comment]
可以的。

1.通过三方serverless平台部署的，可以集成一下第三方的pusher[https://pusher.com](https://pusher.com/pricing)，实现sydney的wss链接中转。
2.自己买科学服务器部署的，可以直接把syd通过自己的服务代理中转就行。

**Comment by adams549659584** [comment]
web 页面无法做到，插件和服务器可以，最新版代码已上传。
