### ISSUE TITLE
设置了x-forward-for之后，可以对话，但是无法返回图片，是什么情况？

### ISSUE THREAD

**Issue by xiansen523** [adams549659584/go-proxy-bingai#69]
![image](https://github.com/adams549659584/go-proxy-bingai/assets/24784452/8a8c9577-5753-472c-be68-b056214d3ed8)
求教一下大佬，设置了x-forward-for之后，可以对话了，但是无法返回生成的图片，是还要设置什么吗？如图。
![微信截图_20230525122353](https://github.com/adams549659584/go-proxy-bingai/assets/24784452/661da560-4bcd-4925-b476-95d90034a00e)

**Comment by shangaokun** [comment]
设置里面的用户设置加了没？

**Comment by xiansen523** [comment]
> 设置里面的用户设置加了没？

加了，你看截图，已经可以对话20条了，在小窗口可以绘图，但是在聊天窗口，返回不了图片，求教大佬，这个要怎么解决

**Comment by gitMFQ** [comment]
是bug，开发者的主站1.7.1版是能收到图片的

**Comment by adams549659584** [comment]
可能反代之类的设置有问题，这块代码没动的
