### ISSUE TITLE
聊天服务器无法搭建

### ISSUE THREAD

**Issue by VireOlive** [adams549659584/go-proxy-bingai#73]
![Screenshot_20230525_220423_com microsoft emmx](https://github.com/adams549659584/go-proxy-bingai/assets/132829327/3eb327c3-4abc-454b-8872-75dc5a55f6a1)
有大佬解释下吗？谢谢。

**Comment by VireOlive** [comment]
好的。不知为何刚刚显示不可用。谢谢！

**Comment by ErlendLee** [comment]
> ![image](https://user-images.githubusercontent.com/10492939/240940761-05b1ff16-c039-4be4-8861-5c65a2305f48.png) 这样就是已经搭建好了的，填在自定义中，选择就能用了

我自己开的聊天服务器怎么一直都不可用
![image](https://github.com/adams549659584/go-proxy-bingai/assets/31845552/4eb0e6f3-1498-490a-af83-fa0b6daacb75)

**Comment by ErlendLee** [comment]
> ![image](https://user-images.githubusercontent.com/10492939/240940761-05b1ff16-c039-4be4-8861-5c65a2305f48.png) 这样就是已经搭建好了的，填在自定义中，选择就能用了

为什么我自己尝试搭建的聊天服务器一直都不能用：https://bing.leeerlend.workers.dev/

**Comment by adams549659584** [comment]
> > ![image](https://user-images.githubusercontent.com/10492939/240940761-05b1ff16-c039-4be4-8861-5c65a2305f48.png) 这样就是已经搭建好了的，填在自定义中，选择就能用了
> 
> 为什么我自己尝试搭建的聊天服务器一直都不能用：https://bing.leeerlend.workers.dev/

我这边试这个链接是可以的

**Comment by ErlendLee** [comment]
> > > ![image](https://user-images.githubusercontent.com/10492939/240940761-05b1ff16-c039-4be4-8861-5c65a2305f48.png) 这样就是已经搭建好了的，填在自定义中，选择就能用了
> > 
> > 
> > 为什么我自己尝试搭建的聊天服务器一直都不能用：https://bing.leeerlend.workers.dev/
> 
> 我这边试这个链接是可以的

我是用vercel搭建的，这个一直报连接失败，但是你的默认的那个地址是可以的。
![image](https://github.com/adams549659584/go-proxy-bingai/assets/31845552/a432fad5-bbeb-46eb-8090-09842e86a0c8)

**Comment by adams549659584** [comment]
你绑个域名试试，可能域名被墙了吧
