### ISSUE TITLE
通过docker部署,问了问题后，点新主题，下一次问题必定报错，按F5刷新或者一键重置页面，都不会出现这个问题。 大佬的线上版本不会有这个问题，一键部署也没有这个问题，不确定我的配置问题出在哪

### ISSUE THREAD

**Issue by arvin915** [adams549659584/go-proxy-bingai#75]

**Comment by arvin915** [comment]
![企业微信截图_16850314519199](https://github.com/adams549659584/go-proxy-bingai/assets/31610047/26473f36-d8d8-4e80-b6a4-183ce95c12c2)

**Comment by adams549659584** [comment]
这样看不出什么，你的配置可以参考下 #71

**Comment by Stiggiee** [comment]
同样的问题，点击新主题后，必须要重置才能用，不然就报错

**Comment by arvin915** [comment]
location /sydney/ChatHub {
    proxy_pass http://127.0.0.1:8080;
    proxy_http_version                 1.1;
#    proxy_set_header Upgrade           $http_upgrade;
    if ($http_upgrade != "websocket") {
    set $http_connection "";
}
#    proxy_set_header Connection        $connection_upgrade;
    proxy_set_header Host              $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host  $host;
    proxy_set_header X-Forwarded-Port  $server_port;
}

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.

    proxy_pass http://127.0.0.1:8080;
    proxy_set_header Host              $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host  $host;
    proxy_set_header X-Forwarded-Port  $server_port;








        }

**Comment by arvin915** [comment]
@adams549659584 
#    proxy_set_header Upgrade           $http_upgrade;
#    proxy_set_header Connection        $connection_upgrade;
现有nginx配置不了这个，就用如下替换了
    if ($http_upgrade != "websocket") {
    set $http_connection "";
}

**Comment by adams549659584** [comment]
我的nginx 也就那些配置，看不出啥问题

**Comment by arvin915** [comment]
> 我的nginx 也就那些配置，看不出啥问题

尝试用了apache做反向代理，一样的，我测试了一下，出现问题时，网络也没有请求，是不是在提交问题前前端有什么逻辑判断？

**Comment by arvin915** [comment]
> 同样的问题，点击新主题后，必须要重置才能用，不然就报错

突发奇想，开无痕模式后，没问题了，你可以尝试下
