### ISSUE TITLE
challenges.cloudflare.com 403

### ISSUE THREAD

**Issue by viqbgrg** [adams549659584/go-proxy-bingai#79]
https://challenges.cloudflare.com/cdn-cgi/challenge-platform    403
看到这样一个错误,这个是什么意思?

**Comment by adams549659584** [comment]
触发 cloudflare 验证了，要去 www.bing.com 官网通过验证

**Comment by viqbgrg** [comment]
这个是代理服务器触发的吧?

**Comment by adams549659584** [comment]
之前不用没启用聊天服务器代理，直连官网的，多人使用同一个账号，也会触发的。

**Comment by adams549659584** [comment]
针对账号的，未登录暂时不会触发。

**Comment by viqbgrg** [comment]
还有一个问题,有时候报错,然后 turing/conversation/create 这个接口返回的是空白数据,这个是怎么回事?

**Comment by adams549659584** [comment]
微软的接口来的，不稳定，所以有加了几次重试的

**Comment by viqbgrg** [comment]
我这边有时候直接不调用create这个接口,调用完/sysconf这个接口就没有了,然后提示这个 很抱歉，似乎出现错误。 让我们重新开始吧。

**Comment by adams549659584** [comment]
> 我这边有时候直接不调用create这个接口,调用完/sysconf这个接口就没有了,然后提示这个 很抱歉，似乎出现错误。 让我们重新开始吧。

你看看有没有其他错误吧，猜不出什么原因

**Comment by viqbgrg** [comment]
控制台也没有报错啊
