### ISSUE TITLE
这里带什么广告跟踪吗？手机和电脑上都打不开

### ISSUE THREAD

**Issue by mwnu** [adams549659584/go-proxy-bingai#80]
就一直转圈，加载不出页面。
控制台显示访问不了google-analytics的页面：

![Snipaste_222](https://github.com/adams549659584/go-proxy-bingai/assets/45463732/6a7b7339-51c0-44f4-b1f1-d69211c02264)

**Comment by adams549659584** [comment]
![image](https://github.com/adams549659584/go-proxy-bingai/assets/10492939/e5639d1b-54d1-4091-bbfa-20dec3db4262)
脚本加载失败了，GA 做使用统计，没广告

**Comment by mwnu** [comment]
> ![image](https://user-images.githubusercontent.com/10492939/241106194-e5639d1b-54d1-4091-bbfa-20dec3db4262.png) 脚本加载失败了，GA 做使用统计，没广告

之前好好的，docker更新到v1.8.1就这样了。

**Comment by adams549659584** [comment]
一键重置下看看，这些一直都有的，所有配置参考下 #71

**Comment by mwnu** [comment]
> 一键重置下看看，这些一直都有的，所有配置参考下 #71

我重新配置了ngnix反向代理，问题没有解决
```
    location / {
        proxy_set_header Host              $host;    
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;
        proxy_pass http://localhost:7877;
    }

    location /sydney/ChatHub {
        proxy_http_version                 1.1;
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        $connection_upgrade;
        proxy_set_header Host              $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;
        proxy_pass http://localhost:7877;
    }

    location ~ .*\.(js|css|jpg|jpeg|gif|png|ico|pdf|txt)$ {
      proxy_pass http://localhost:7877;
    }
```

**Comment by mwnu** [comment]
> 一键重置下看看，这些一直都有的，所有配置参考下 #71

我想找出问题所在了：环境变量中加了# 简单授权认证密码 Go_Proxy_BingAI_AUTH_KEY 就会加载出来

**Comment by adams549659584** [comment]
> > 一键重置下看看，这些一直都有的，所有配置参考下 #71
> 
> 我想找出问题所在了：环境变量中加了# 简单授权认证密码 Go_Proxy_BingAI_AUTH_KEY 就会加载出来

我看看

**Comment by mwnu** [comment]
> > > 一键重置下看看，这些一直都有的，所有配置参考下 #71
> > 
> > 
> > 我想找出问题所在了：环境变量中加了# 简单授权认证密码 Go_Proxy_BingAI_AUTH_KEY 就会加载出来
> 
> 我看看

配置了 Go_Proxy_BingAI_AUTH_KEY会加载不出来，前面少打一个字

**Comment by adams549659584** [comment]
> > > > 一键重置下看看，这些一直都有的，所有配置参考下 #71
> > > 
> > > 
> > > 我想找出问题所在了：环境变量中加了# 简单授权认证密码 Go_Proxy_BingAI_AUTH_KEY 就会加载出来
> > 
> > 
> > 我看看
> 
> 配置了 Go_Proxy_BingAI_AUTH_KEY会加载不出来，前面少打一个字

v1.8.2 已修复
