### ISSUE TITLE
原来用着挺稳的，更新之后网络基本上就连不上了

### ISSUE THREAD

**Issue by mwnu** [adams549659584/go-proxy-bingai#84]
更新后一打开有三个服务器可选择，可以ping通（显示延迟时断时续的），但都连不上。
我之前用本地服务器代理的用了半个月都没掉过线。
尝试coludflare自建worker作为自定义服务器也不行。
我电脑上挂梯子是可以直接用new bing的，但选第一个官方的服务器也还是不行。
![1111](https://github.com/adams549659584/go-proxy-bingai/assets/45463732/11620481-7625-4c2a-8764-aa7546868561)

**Comment by adams549659584** [comment]
![image](https://github.com/adams549659584/go-proxy-bingai/assets/10492939/21385fd5-b352-4c10-b579-26c8f8b39a16)
触发 cloudflare 验证了，得去 www.bing.com 过验证

**Comment by mwnu** [comment]
> ![image](https://user-images.githubusercontent.com/10492939/241174778-21385fd5-b352-4c10-b579-26c8f8b39a16.png) 触发 cloudflare 验证了，得去 [www.bing.com](http://www.bing.com) 过验证

又加载不了页面了，把授权密码和cookie变量都去了都进不了

**Comment by mwnu** [comment]
> ![image](https://user-images.githubusercontent.com/10492939/241174778-21385fd5-b352-4c10-b579-26c8f8b39a16.png) 触发 cloudflare 验证了，得去 [www.bing.com](http://www.bing.com) 过验证

docker 的[adams549659584/go-proxy-bingai:latest](https://registry.hub.docker.com/layers/adams549659584/go-proxy-bingai/latest/images/sha256-b7c90059b91c8af37cb7db472f3183756c60ce9a15586bcc4092583424dc3270?context=explore)我这边拉取的是v1.8.1？
一直重置，换设备都是1.8.1，难道我拉的镜像有问题？
