### ISSUE TITLE
请问下，bing官方和本站是什么区别

### ISSUE THREAD

**Issue by justincnn** [adams549659584/go-proxy-bingai#85]
![截屏2023-05-26 19.34.22.png](https://img1.imgtp.com/2023/05/26/rARkW20v.png)

感谢大神的更新，一天之后就可以使用了。

不过更新了新版本不能画画了，有哪里需要重新设置么？

**Comment by adams549659584** [comment]
![1685108654570](https://github.com/adams549659584/go-proxy-bingai/assets/10492939/23562214-36cc-4c39-93f3-5425b2085a9e)
官方能用的话，推荐用官方，本站是反代聊天服务，会慢
似乎没改动到画图，我试了下我的还能画图的。
