### ISSUE TITLE
CORS和“/turing/conversation/chats”路由请求错误

### ISSUE THREAD

**Issue by mwnu** [adams549659584/go-proxy-bingai#87]
首先我通过nginx反代，用https+端口访问UI页面，例如：https://a.example.com:7878，
它会请求https://a.example.com/turing/conversation/chats，显然是访问不到资源的。
然后就出现WebSocket connection to 'wss://xxxx:7878/sydney/ChatHub' failed:，说什么不存在“Access-Control-Allow-Origin”标头。
有一定几率无法成功创建对话。
![333](https://github.com/adams549659584/go-proxy-bingai/assets/45463732/632263fc-b642-41f3-b3d9-f6eae33f666e)
![4444](https://github.com/adams549659584/go-proxy-bingai/assets/45463732/6b36f202-eae8-4c2f-9c78-00a5986b013b)

**Comment by mwnu** [comment]
如果增加下面这几个环境变量，初始会话时就会在控制台一直刷新上述错误，在页面上显示正在连接中.....连接失败，如果不加环境变量（匿名会话），虽然也会出现上述错误，但是能够正常生成回复：
```
Go_Proxy_BingAI_USER_TOKEN_1=xxx
Go_Proxy_BingAI_USER_TOKEN_2=xxx
Go_Proxy_BingAI_USER_TOKEN_3=xxx ...
# 简单授权认证密码，可选
Go_Proxy_BingAI_AUTH_KEY=xxx
```

**Comment by adams549659584** [comment]
更新1.8.2看看

**Comment by mwnu** [comment]
> 更新1.8.2看看
更不到，docker 的latest镜像安装之后仍然显示1.8.1，看我另一个Issues

**Comment by macvip** [comment]
> 更新1.8.2看看
> 更不到，docker 的latest镜像安装之后仍然显示1.8.1，看我另一个Issues

好像作者忘了更新web目录下相应的文件了

**Comment by adams549659584** [comment]
> > 更新1.8.2看看
> > 更不到，docker 的latest镜像安装之后仍然显示1.8.1，看我另一个Issues
> 
> 好像作者忘了更新web目录下相应的文件了

是的，明后天再改下
