### ISSUE TITLE
不能切换对话样式，不能设置用户

### ISSUE THREAD

**Issue by mwnu** [adams549659584/go-proxy-bingai#88]
可以对话，但是一旦切换对话样式（即便再切回来），就会出现“很抱歉，似乎出现错误。让我们重新开始吧”。
前端设置用户cookie不起作用，新的对话不会同步到聊天记录里。
版本：1.8.1
客户端：手机版

**Comment by mwnu** [comment]
我的主浏览器没有清除过cookie和缓存，也没用重置过，就一直可以正常使用。
但是新开客户端，或者换别的设备，就有这样或那样的问题。
可能跟没有加载正确的资源有关。

**Comment by adams549659584** [comment]
基本只支持比较新的浏览器的
