### ISSUE TITLE
部署的cf workers服务器总是不可用

### ISSUE THREAD

**Issue by SokWith** [adams549659584/go-proxy-bingai#90]
访问部署的服务器域名，出现这个：
<h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p>01sFwZAAAAAB8WWiYXwfATLoX/Vk4I7SCTFRTRURHRTA4MTUARWRnZQ==

**Comment by adams549659584** [comment]
这样就是已经部署好了的，点多几次检测看看，一般需要绑定个域名

**Comment by SokWith** [comment]
> 

谢谢。
原来使用自定义服务器需要写全 https://域名

**Comment by lilPiper** [comment]
打扰了。请问是 CF 的 IP 有问题吗？还是要再套 nginx 之类的
目前出现了相同的报错

**Comment by SokWith** [comment]
> 打扰了。请问是 CF 的 IP 有问题吗？还是要再套 nginx 之类的 目前出现了相同的报错

@lilPiper cf没问题。前面的信息已经说得很清楚了，服务器返回的信息是正确的。在填写自定义服务器时需要把   https://域名 写全。

**Comment by lilPiper** [comment]
谢谢您的指教！您在另一个 issue 下的回答对我帮助很大！

#https://github.com/adams549659584/go-proxy-bingai/issues/81#issuecomment-1567050101

用 railway 的自带域名 `*.railway.app` 能运行，也搞了 HTTPS 证书，DNS 由 CF 托管。我的问题在于设置 CF 的路由不对而且没设置严格加密模式。

#https://github.com/adams549659584/go-proxy-bingai/issues/81#issuecomment-1569968492

整理了一下方法：

- CF 设置 SSL/TLS encryption mode is Full (strict) 
- 路由要填 `bing.` + `xxx.com`( 自己的域名 ) +`/sydney/*`

**Comment by SokWith** [comment]
> 谢谢您的指教！您在另一个 issue 下的回答对我帮助很大！
> 
> #[#81 (comment)](https://github.com/adams549659584/go-proxy-bingai/issues/81#issuecomment-1567050101)
> 
> 用 railway 的自带域名 `*.railway.app` 能运行，也搞了 HTTPS 证书，DNS 由 CF 托管。我的问题在于设置 CF 的路由不对而且没设置严格加密模式。
> 
> #[#81 (comment)](https://github.com/adams549659584/go-proxy-bingai/issues/81#issuecomment-1569968492)
> 
> 整理了一下方法：
> 
> * CF 设置 SSL/TLS encryption mode is Full (strict)
> * 路由要填 `bing.` + `xxx.com`( 自己的域名 ) +`/sydney/*`

@lilPiper 你这是本站服务器设置方法，自定义是服务器选择的最后一行，是为服务器不能直连www.bing.com用的，也就是官网、cf、本站的服务器都不能连接，仍然可以在使用自定义栏的自建服务器
![image](https://github.com/adams549659584/go-proxy-bingai/assets/129967025/25ffb612-77cd-41dd-bf4a-75f37b62e980)
