### ISSUE TITLE
部署在vercel平台的服务器连接失败

### ISSUE THREAD

**Issue by liguangzhehome** [adams549659584/go-proxy-bingai#91]
![部署](https://github.com/adams549659584/go-proxy-bingai/assets/121355666/8bf40dce-f049-44b9-98b9-3309b9582889)
搭建在vercel平台的连接失败，
![图片2](https://github.com/adams549659584/go-proxy-bingai/assets/121355666/5ebca30e-4467-4a32-aa86-2b518941157b)
示例中的vercel网址同样连接失败

**Comment by adams549659584** [comment]
vercel 不支持 websocket ，所以才搞了 cloudflare ，参考 #81
