### ISSUE TITLE
在docker中部署后无法运行

### ISSUE THREAD

**Issue by Jamesweiym** [adams549659584/go-proxy-bingai#92]
一直卡在这里，请问大佬怎么解决
![截屏2023-05-27 上午12 54 12](https://github.com/adams549659584/go-proxy-bingai/assets/91742056/7a419b9c-178c-4ea4-90cd-e1a3be50bf66)

**Comment by adams549659584** [comment]
看看有没有报什么错误，可参考 #71

**Comment by sfdzkj** [comment]
配置ssl证书，然后反向代理
