### ISSUE TITLE
一键部署的vercel使用的是谁的cookies？

### ISSUE THREAD

**Issue by SokWith** [adams549659584/go-proxy-bingai#93]
没有做任何修改，就可以使用，难道有内置账户吗？

**Comment by adams549659584** [comment]
匿名可用的，只是画图那些需要登录

**Comment by SokWith** [comment]
> 匿名可用的，只是画图那些需要登录

谢谢。
怎么做到的？微软的官网原来不也是有单一账户24小时次数限制吗？现在取消了？

**Comment by adams549659584** [comment]
单一账户还是有24小时限制的，官网也有匿名的聊天，只是登录单次可以聊20条，未登录可以聊10条

**Comment by SokWith** [comment]
谢谢
