### ISSUE TITLE
GO编译使用 	 Supervisor进程守护运行

### ISSUE THREAD

**Issue by sfdzkj** [adams549659584/go-proxy-bingai#94]
请问这种方式 cookie 如何设置？

**Comment by sfdzkj** [comment]
Docker 好像不能修改默认的Cloudflare地址，想换成自己的。 GO编译  Supervisor进程守护运行不知道cookeie 如何设置

**Comment by adams549659584** [comment]
cookie 一般在前台设置，想在服务器设置，参考 README 中的环境变量，不过不推荐服务器设置给多人使用，cloudflare 地址暂时不能配置，可在前台自定义添加，或修改源码 https://github.com/adams549659584/go-proxy-bingai/blob/master/frontend/src/stores/modules/chat/index.ts#L25 重新编译。
