### ISSUE TITLE
本机部署成功，但是局域网没法访问

### ISSUE THREAD

**Issue by QwindF** [adams549659584/go-proxy-bingai#97]
![image](https://github.com/adams549659584/go-proxy-bingai/assets/87116340/c06b8ee6-7b17-4ac7-8b43-a0eceb87a5a3)
![image](https://github.com/adams549659584/go-proxy-bingai/assets/87116340/198895e9-b9ef-499c-884c-206a088ce314)
![image](https://github.com/adams549659584/go-proxy-bingai/assets/87116340/c922d5b7-e7d5-4c1c-9486-198518523ca4)

**Comment by adams549659584** [comment]
除了本地，其他访问只支持 https ，部署参考 #71
